/* Made by scripts/generate.mjs from icons/*.ts and icons.json. Do not edit; run `npm run generate`. */

export type { Icon, IconElement, IconNode, IconOptions } from "./types";
export { DEFAULTS, createElement, svgAttributes, toSvg } from "./render";
export { iconNames, loadIcon } from "./dynamic";

export { ChevronRightIcon, ChevronRightIcon as ChevronIcon, ChevronRightIcon as PathStepIcon } from "./icons/chevron-right";
export { ChevronLeftIcon } from "./icons/chevron-left";
export { ChevronDownIcon, ChevronDownIcon as DisclosureIcon } from "./icons/chevron-down";
export { ChevronUpIcon } from "./icons/chevron-up";
export { ArrowRightIcon, ArrowRightIcon as ArrowRight } from "./icons/arrow-right";
export { ArrowLeftIcon, ArrowLeftIcon as ArrowLeft } from "./icons/arrow-left";
export { ArrowDownIcon, ArrowDownIcon as SortDownIcon } from "./icons/arrow-down";
export { ArrowUpIcon, ArrowUpIcon as SortUpIcon } from "./icons/arrow-up";
export { CheckIcon, CheckIcon as Check } from "./icons/check";
export { XIcon, XIcon as CloseIcon, XIcon as X } from "./icons/x";
export { PlusIcon } from "./icons/plus";
export { MinusIcon } from "./icons/minus";
export { MenuIcon } from "./icons/menu";
export { EllipsisIcon } from "./icons/ellipsis";
export { SpinnerIcon, SpinnerIcon as Loader2, SpinnerIcon as Loader2Icon } from "./icons/spinner";
export { SquareIcon } from "./icons/square";
export { SearchIcon } from "./icons/search";
export { ExternalIcon } from "./icons/external";
export { CopyIcon } from "./icons/copy";
export { TrashIcon, TrashIcon as Trash2Icon } from "./icons/trash";
export { DownloadIcon } from "./icons/download";
export { UploadIcon } from "./icons/upload";
export { ExternalLinkIcon, ExternalLinkIcon as ExternalLink } from "./icons/external-link";
export { PencilIcon } from "./icons/pencil";
export { SaveIcon } from "./icons/save";
export { EraserIcon } from "./icons/eraser";
export { RefreshCwIcon } from "./icons/refresh-cw";
export { RotateCcwIcon, RotateCcwIcon as AgainIcon } from "./icons/rotate-ccw";
export { RotateCwIcon, RotateCwIcon as RotateCw } from "./icons/rotate-cw";
export { Undo2Icon } from "./icons/undo2";
export { Redo2Icon } from "./icons/redo2";
export { ScissorsIcon } from "./icons/scissors";
export { ClipboardIcon } from "./icons/clipboard";
export { ClipboardPasteIcon } from "./icons/clipboard-paste";
export { PinIcon } from "./icons/pin";
export { FoldVerticalIcon } from "./icons/fold-vertical";
export { WrapTextIcon } from "./icons/wrap-text";
export { LinkIcon, LinkIcon as Link2Icon } from "./icons/link";
export { PaperclipIcon } from "./icons/paperclip";
export { LogOutIcon } from "./icons/log-out";
export { MaximizeIcon, MaximizeIcon as Maximize2 } from "./icons/maximize";
export { MinimizeIcon, MinimizeIcon as Minimize2 } from "./icons/minimize";
export { PanelLeftCloseIcon } from "./icons/panel-left-close";
export { PanelLeftOpenIcon } from "./icons/panel-left-open";
export { SquareArrowOutUpRightIcon } from "./icons/square-arrow-out-up-right";
export { TriangleAlertIcon, TriangleAlertIcon as WarnIcon } from "./icons/triangle-alert";
export { InfoIcon } from "./icons/info";
export { CircleCheckIcon } from "./icons/circle-check";
export { OctagonXIcon } from "./icons/octagon-x";
export { BanIcon } from "./icons/ban";
export { LockIcon, LockIcon as LockedIcon } from "./icons/lock";
export { KeyRoundIcon } from "./icons/key-round";
export { ShieldIcon } from "./icons/shield";
export { ShieldAlertIcon } from "./icons/shield-alert";
export { ShieldPlusIcon } from "./icons/shield-plus";
export { SparklesIcon, SparklesIcon as Sparkles } from "./icons/sparkles";
export { StarIcon } from "./icons/star";
export { LightbulbIcon, LightbulbIcon as Lightbulb } from "./icons/lightbulb";
export { EyeIcon } from "./icons/eye";
export { ClockIcon, ClockIcon as RecentsIcon } from "./icons/clock";
export { GaugeIcon } from "./icons/gauge";
export { GemIcon } from "./icons/gem";
export { HomeIcon, HomeIcon as Home } from "./icons/home";
export { UserRoundIcon } from "./icons/user-round";
export { UsersIcon } from "./icons/users";
export { MailIcon } from "./icons/mail";
export { MessageSquareIcon } from "./icons/message-square";
export { BotIcon } from "./icons/bot";
export { BugIcon } from "./icons/bug";
export { BookOpenIcon } from "./icons/book-open";
export { LibraryIcon } from "./icons/library";
export { CreditCardIcon } from "./icons/credit-card";
export { TagIcon } from "./icons/tag";
export { PackageIcon } from "./icons/package";
export { ArchiveIcon } from "./icons/archive";
export { MapIcon } from "./icons/map";
export { LifeBuoyIcon } from "./icons/life-buoy";
export { WrenchIcon } from "./icons/wrench";
export { PlugIcon } from "./icons/plug";
export { PlugZapIcon } from "./icons/plug-zap";
export { ServerIcon } from "./icons/server";
export { CloudIcon } from "./icons/cloud";
export { GlobeIcon } from "./icons/globe";
export { MonitorIcon, MonitorIcon as DesktopIcon } from "./icons/monitor";
export { TabletIcon } from "./icons/tablet";
export { SmartphoneIcon, SmartphoneIcon as PhoneIcon } from "./icons/smartphone";
export { TerminalIcon, TerminalIcon as Terminal } from "./icons/terminal";
export { CodeIcon } from "./icons/code";
export { SettingsIcon, SettingsIcon as SlidersHorizontalIcon } from "./icons/settings";
export { FileTextIcon } from "./icons/file-text";
export { FilePlusIcon } from "./icons/file-plus";
export { FileMinusIcon } from "./icons/file-minus";
export { FilePenIcon } from "./icons/file-pen";
export { FileSearchIcon } from "./icons/file-search";
export { FileCodeIcon, FileCodeIcon as FileCode2 } from "./icons/file-code";
export { FileVideoIcon } from "./icons/file-video";
export { FolderIcon } from "./icons/folder";
export { FolderPlusIcon } from "./icons/folder-plus";
export { FolderCogIcon } from "./icons/folder-cog";
export { FoldersIcon } from "./icons/folders";
export { FolderTreeIcon } from "./icons/folder-tree";
export { ImageIcon } from "./icons/image";
export { ImagePlayIcon } from "./icons/image-play";
export { MusicIcon } from "./icons/music";
export { CaptionsIcon } from "./icons/captions";
export { BoldIcon } from "./icons/bold";
export { ItalicIcon } from "./icons/italic";
export { UnderlineIcon } from "./icons/underline";
export { StrikethroughIcon } from "./icons/strikethrough";
export { Heading2Icon } from "./icons/heading2";
export { QuoteIcon } from "./icons/quote";
export { ListIcon } from "./icons/list";
export { ListOrderedIcon } from "./icons/list-ordered";
export { CodeAppIcon } from "./icons/code-app";
export { FinderAppIcon } from "./icons/finder-app";
export { MediaAppIcon } from "./icons/media-app";
export { PageAppIcon } from "./icons/page-app";
export { PortfolioAppIcon } from "./icons/portfolio-app";
export { CvAppIcon } from "./icons/cv-app";
export { HelpAppIcon } from "./icons/help-app";
export { SupportAppIcon } from "./icons/support-app";
export { StoryAppIcon } from "./icons/story-app";
export { CoursesAppIcon } from "./icons/courses-app";
export { TermsAppIcon } from "./icons/terms-app";
export { PrivacyAppIcon } from "./icons/privacy-app";
export { AcceptableUseAppIcon } from "./icons/acceptable-use-app";
export { CookiesAppIcon } from "./icons/cookies-app";
export { RefundsAppIcon } from "./icons/refunds-app";
export { AppsIcon } from "./icons/apps";
export { VideoGroupIcon, VideoGroupIcon as VideosKindIcon } from "./icons/video-group";
export { ImageGroupIcon, ImageGroupIcon as ImagesKindIcon } from "./icons/image-group";
export { AudioGroupIcon, AudioGroupIcon as AudioKindIcon } from "./icons/audio-group";
export { PdfGroupIcon, PdfGroupIcon as DocumentsKindIcon } from "./icons/pdf-group";
export { AnimateGroupIcon } from "./icons/animate-group";
export { SubtitleGroupIcon } from "./icons/subtitle-group";
export { QueueIcon } from "./icons/queue";
export { ProIcon } from "./icons/pro";
export { VideoShrinkIcon } from "./icons/video-shrink";
export { FitSizeIcon } from "./icons/fit-size";
export { TrimIcon } from "./icons/trim";
export { ConvertIcon } from "./icons/convert";
export { VideoToGifIcon } from "./icons/video-to-gif";
export { ResizeIcon } from "./icons/resize";
export { MuteIcon } from "./icons/mute";
export { ImageShrinkIcon } from "./icons/image-shrink";
export { LongestEdgeIcon } from "./icons/longest-edge";
export { StripDataIcon } from "./icons/strip-data";
export { AudioShrinkIcon } from "./icons/audio-shrink";
export { VoiceIcon } from "./icons/voice";
export { PdfShrinkIcon } from "./icons/pdf-shrink";
export { GrayscaleIcon } from "./icons/grayscale";
export { MakeAnimationIcon } from "./icons/make-animation";
export { WriteSubtitlesIcon } from "./icons/write-subtitles";
export { TranscribeIcon } from "./icons/transcribe";
export { BurnInIcon } from "./icons/burn-in";
export { SubtitleTrackIcon } from "./icons/subtitle-track";
export { ToolsIcon } from "./icons/tools";
export { PlayIcon } from "./icons/play";
export { PauseIcon } from "./icons/pause";
export { NewIcon } from "./icons/new";
export { ProjectsIcon } from "./icons/projects";
export { FilesIcon } from "./icons/files";
export { AgentIcon } from "./icons/agent";
export { PackagesIcon } from "./icons/packages";
export { ShareIcon } from "./icons/share";
export { AllFilesIcon } from "./icons/all-files";
export { PublicIcon } from "./icons/public";
export { IconsViewIcon } from "./icons/icons-view";
export { ListViewIcon } from "./icons/list-view";
export { ColumnsViewIcon } from "./icons/columns-view";
export { GalleryViewIcon } from "./icons/gallery-view";
export { SmallTilesIcon } from "./icons/small-tiles";
export { LargeTilesIcon } from "./icons/large-tiles";
export { CommandKeyIcon } from "./icons/command-key";
export { ShiftKeyIcon } from "./icons/shift-key";
export { LayersIcon } from "./icons/layers";
export { BlocksIcon } from "./icons/blocks";
export { GripIcon } from "./icons/grip";
export { EyeOffIcon } from "./icons/eye-off";
export { UnlockIcon } from "./icons/unlock";
export { DuplicateIcon } from "./icons/duplicate";
export { AlignLeftIcon } from "./icons/align-left";
export { AlignCenterIcon } from "./icons/align-center";
export { AlignRightIcon } from "./icons/align-right";
export { PanIcon } from "./icons/pan";
export { FitScreenIcon } from "./icons/fit-screen";
export { PageBreakIcon } from "./icons/page-break";
export { PublishIcon } from "./icons/publish";
export { TemplateIcon } from "./icons/template";
export { VersionsIcon } from "./icons/versions";
export { SectionIcon } from "./icons/section";
export { TextIcon } from "./icons/text";
export { FormIcon } from "./icons/form";
export { SpreadsheetIcon } from "./icons/spreadsheet";
export { PresentationIcon } from "./icons/presentation";
export { RunSnipMark } from "./icons/run-snip-mark";
export { RunSnipWordmark } from "./icons/run-snip-wordmark";
export { IconGoogle } from "./icons/icon-google";
export { IconGithub } from "./icons/icon-github";
