/* Made by scripts/generate.mjs from icons/*.ts and icons.json. Do not edit; run `npm run generate`. */

import { createIcon, type IconComponent } from "./create";
import ChevronRightIconData from "../icons/chevron-right";
import ChevronLeftIconData from "../icons/chevron-left";
import ChevronDownIconData from "../icons/chevron-down";
import ChevronUpIconData from "../icons/chevron-up";
import ArrowRightIconData from "../icons/arrow-right";
import ArrowLeftIconData from "../icons/arrow-left";
import ArrowDownIconData from "../icons/arrow-down";
import ArrowUpIconData from "../icons/arrow-up";
import CheckIconData from "../icons/check";
import XIconData from "../icons/x";
import PlusIconData from "../icons/plus";
import MinusIconData from "../icons/minus";
import MenuIconData from "../icons/menu";
import EllipsisIconData from "../icons/ellipsis";
import SpinnerIconData from "../icons/spinner";
import SquareIconData from "../icons/square";
import SearchIconData from "../icons/search";
import ExternalIconData from "../icons/external";
import CopyIconData from "../icons/copy";
import TrashIconData from "../icons/trash";
import DownloadIconData from "../icons/download";
import UploadIconData from "../icons/upload";
import ExternalLinkIconData from "../icons/external-link";
import PencilIconData from "../icons/pencil";
import SaveIconData from "../icons/save";
import EraserIconData from "../icons/eraser";
import RefreshCwIconData from "../icons/refresh-cw";
import RotateCcwIconData from "../icons/rotate-ccw";
import RotateCwIconData from "../icons/rotate-cw";
import Undo2IconData from "../icons/undo2";
import Redo2IconData from "../icons/redo2";
import ScissorsIconData from "../icons/scissors";
import ClipboardIconData from "../icons/clipboard";
import ClipboardPasteIconData from "../icons/clipboard-paste";
import PinIconData from "../icons/pin";
import FoldVerticalIconData from "../icons/fold-vertical";
import WrapTextIconData from "../icons/wrap-text";
import LinkIconData from "../icons/link";
import PaperclipIconData from "../icons/paperclip";
import LogOutIconData from "../icons/log-out";
import MaximizeIconData from "../icons/maximize";
import MinimizeIconData from "../icons/minimize";
import PanelLeftCloseIconData from "../icons/panel-left-close";
import PanelLeftOpenIconData from "../icons/panel-left-open";
import SquareArrowOutUpRightIconData from "../icons/square-arrow-out-up-right";
import TriangleAlertIconData from "../icons/triangle-alert";
import InfoIconData from "../icons/info";
import CircleCheckIconData from "../icons/circle-check";
import OctagonXIconData from "../icons/octagon-x";
import BanIconData from "../icons/ban";
import LockIconData from "../icons/lock";
import KeyRoundIconData from "../icons/key-round";
import ShieldIconData from "../icons/shield";
import ShieldAlertIconData from "../icons/shield-alert";
import ShieldPlusIconData from "../icons/shield-plus";
import SparklesIconData from "../icons/sparkles";
import StarIconData from "../icons/star";
import LightbulbIconData from "../icons/lightbulb";
import EyeIconData from "../icons/eye";
import ClockIconData from "../icons/clock";
import GaugeIconData from "../icons/gauge";
import GemIconData from "../icons/gem";
import HomeIconData from "../icons/home";
import UserRoundIconData from "../icons/user-round";
import UsersIconData from "../icons/users";
import MailIconData from "../icons/mail";
import MessageSquareIconData from "../icons/message-square";
import BotIconData from "../icons/bot";
import BugIconData from "../icons/bug";
import BookOpenIconData from "../icons/book-open";
import LibraryIconData from "../icons/library";
import CreditCardIconData from "../icons/credit-card";
import TagIconData from "../icons/tag";
import PackageIconData from "../icons/package";
import ArchiveIconData from "../icons/archive";
import MapIconData from "../icons/map";
import LifeBuoyIconData from "../icons/life-buoy";
import WrenchIconData from "../icons/wrench";
import PlugIconData from "../icons/plug";
import PlugZapIconData from "../icons/plug-zap";
import ServerIconData from "../icons/server";
import CloudIconData from "../icons/cloud";
import GlobeIconData from "../icons/globe";
import MonitorIconData from "../icons/monitor";
import TabletIconData from "../icons/tablet";
import SmartphoneIconData from "../icons/smartphone";
import TerminalIconData from "../icons/terminal";
import CodeIconData from "../icons/code";
import SettingsIconData from "../icons/settings";
import FileTextIconData from "../icons/file-text";
import FilePlusIconData from "../icons/file-plus";
import FileMinusIconData from "../icons/file-minus";
import FilePenIconData from "../icons/file-pen";
import FileSearchIconData from "../icons/file-search";
import FileCodeIconData from "../icons/file-code";
import FileVideoIconData from "../icons/file-video";
import FolderIconData from "../icons/folder";
import FolderPlusIconData from "../icons/folder-plus";
import FolderCogIconData from "../icons/folder-cog";
import FoldersIconData from "../icons/folders";
import FolderTreeIconData from "../icons/folder-tree";
import ImageIconData from "../icons/image";
import ImagePlayIconData from "../icons/image-play";
import MusicIconData from "../icons/music";
import CaptionsIconData from "../icons/captions";
import BoldIconData from "../icons/bold";
import ItalicIconData from "../icons/italic";
import UnderlineIconData from "../icons/underline";
import StrikethroughIconData from "../icons/strikethrough";
import Heading2IconData from "../icons/heading2";
import QuoteIconData from "../icons/quote";
import ListIconData from "../icons/list";
import ListOrderedIconData from "../icons/list-ordered";
import CodeAppIconData from "../icons/code-app";
import FinderAppIconData from "../icons/finder-app";
import MediaAppIconData from "../icons/media-app";
import PageAppIconData from "../icons/page-app";
import PortfolioAppIconData from "../icons/portfolio-app";
import CvAppIconData from "../icons/cv-app";
import HelpAppIconData from "../icons/help-app";
import SupportAppIconData from "../icons/support-app";
import StoryAppIconData from "../icons/story-app";
import CoursesAppIconData from "../icons/courses-app";
import TermsAppIconData from "../icons/terms-app";
import PrivacyAppIconData from "../icons/privacy-app";
import AcceptableUseAppIconData from "../icons/acceptable-use-app";
import CookiesAppIconData from "../icons/cookies-app";
import RefundsAppIconData from "../icons/refunds-app";
import AppsIconData from "../icons/apps";
import VideoGroupIconData from "../icons/video-group";
import ImageGroupIconData from "../icons/image-group";
import AudioGroupIconData from "../icons/audio-group";
import PdfGroupIconData from "../icons/pdf-group";
import AnimateGroupIconData from "../icons/animate-group";
import SubtitleGroupIconData from "../icons/subtitle-group";
import QueueIconData from "../icons/queue";
import ProIconData from "../icons/pro";
import VideoShrinkIconData from "../icons/video-shrink";
import FitSizeIconData from "../icons/fit-size";
import TrimIconData from "../icons/trim";
import ConvertIconData from "../icons/convert";
import VideoToGifIconData from "../icons/video-to-gif";
import ResizeIconData from "../icons/resize";
import MuteIconData from "../icons/mute";
import ImageShrinkIconData from "../icons/image-shrink";
import LongestEdgeIconData from "../icons/longest-edge";
import StripDataIconData from "../icons/strip-data";
import AudioShrinkIconData from "../icons/audio-shrink";
import VoiceIconData from "../icons/voice";
import PdfShrinkIconData from "../icons/pdf-shrink";
import GrayscaleIconData from "../icons/grayscale";
import MakeAnimationIconData from "../icons/make-animation";
import WriteSubtitlesIconData from "../icons/write-subtitles";
import TranscribeIconData from "../icons/transcribe";
import BurnInIconData from "../icons/burn-in";
import SubtitleTrackIconData from "../icons/subtitle-track";
import ToolsIconData from "../icons/tools";
import PlayIconData from "../icons/play";
import PauseIconData from "../icons/pause";
import NewIconData from "../icons/new";
import ProjectsIconData from "../icons/projects";
import FilesIconData from "../icons/files";
import AgentIconData from "../icons/agent";
import PackagesIconData from "../icons/packages";
import ShareIconData from "../icons/share";
import AllFilesIconData from "../icons/all-files";
import PublicIconData from "../icons/public";
import IconsViewIconData from "../icons/icons-view";
import ListViewIconData from "../icons/list-view";
import ColumnsViewIconData from "../icons/columns-view";
import GalleryViewIconData from "../icons/gallery-view";
import SmallTilesIconData from "../icons/small-tiles";
import LargeTilesIconData from "../icons/large-tiles";
import CommandKeyIconData from "../icons/command-key";
import ShiftKeyIconData from "../icons/shift-key";
import LayersIconData from "../icons/layers";
import BlocksIconData from "../icons/blocks";
import GripIconData from "../icons/grip";
import EyeOffIconData from "../icons/eye-off";
import UnlockIconData from "../icons/unlock";
import DuplicateIconData from "../icons/duplicate";
import AlignLeftIconData from "../icons/align-left";
import AlignCenterIconData from "../icons/align-center";
import AlignRightIconData from "../icons/align-right";
import PanIconData from "../icons/pan";
import FitScreenIconData from "../icons/fit-screen";
import PageBreakIconData from "../icons/page-break";
import PublishIconData from "../icons/publish";
import TemplateIconData from "../icons/template";
import VersionsIconData from "../icons/versions";
import SectionIconData from "../icons/section";
import TextIconData from "../icons/text";
import FormIconData from "../icons/form";
import SpreadsheetIconData from "../icons/spreadsheet";
import PresentationIconData from "../icons/presentation";
import RunSnipMarkData from "../icons/run-snip-mark";
import RunSnipWordmarkData from "../icons/run-snip-wordmark";
import IconGoogleData from "../icons/icon-google";
import IconGithubData from "../icons/icon-github";
import CommentAddIconData from "../icons/comment-add";
import CommentsIconData from "../icons/comments";
import ReplyIconData from "../icons/reply";
import ReplyAllIconData from "../icons/reply-all";
import ReopenIconData from "../icons/reopen";
import AtSignIconData from "../icons/at-sign";
import BellIconData from "../icons/bell";
import BellOffIconData from "../icons/bell-off";
import CursorIconData from "../icons/cursor";
import HandIconData from "../icons/hand";
import FollowIconData from "../icons/follow";
import PresenceIconData from "../icons/presence";
import MoreVerticalIconData from "../icons/more-vertical";
import ChevronsUpDownIconData from "../icons/chevrons-up-down";
import ChevronsLeftIconData from "../icons/chevrons-left";
import ChevronsRightIconData from "../icons/chevrons-right";
import ExpandIconData from "../icons/expand";
import CollapseIconData from "../icons/collapse";
import SunIconData from "../icons/sun";
import MoonIconData from "../icons/moon";
import HelpCircleIconData from "../icons/help-circle";
import ThumbsUpIconData from "../icons/thumbs-up";
import PaletteIconData from "../icons/palette";
import DropletIconData from "../icons/droplet";
import MicIconData from "../icons/mic";
import MicOffIconData from "../icons/mic-off";
import KeyboardIconData from "../icons/keyboard";
import TranslateIconData from "../icons/translate";
import SendIconData from "../icons/send";
import InboxIconData from "../icons/inbox";
import ActivityIconData from "../icons/activity";
import PanelRightOpenIconData from "../icons/panel-right-open";
import PanelRightCloseIconData from "../icons/panel-right-close";
import LayoutGridIconData from "../icons/layout-grid";
import SortIconData from "../icons/sort";
import LassoIconData from "../icons/lasso";
import TableIconData from "../icons/table";
import ShapesIconData from "../icons/shapes";
import TextBoxIconData from "../icons/text-box";
import EquationIconData from "../icons/equation";
import SymbolIconData from "../icons/symbol";
import EmojiIconData from "../icons/emoji";
import CalendarIconData from "../icons/calendar";
import DateTimeIconData from "../icons/date-time";
import HeaderIconData from "../icons/header";
import FooterIconData from "../icons/footer";
import PageNumberIconData from "../icons/page-number";
import FootnoteIconData from "../icons/footnote";
import BookmarkIconData from "../icons/bookmark";
import TableOfContentsIconData from "../icons/table-of-contents";
import UnlinkIconData from "../icons/unlink";
import ImagePlusIconData from "../icons/image-plus";
import WatermarkIconData from "../icons/watermark";
import SectionBreakIconData from "../icons/section-break";
import PortraitPageIconData from "../icons/portrait-page";
import LandscapePageIconData from "../icons/landscape-page";
import MarginsIconData from "../icons/margins";
import PageSizeIconData from "../icons/page-size";
import RulerIconData from "../icons/ruler";
import ZoomInIconData from "../icons/zoom-in";
import ZoomOutIconData from "../icons/zoom-out";
import FitWidthIconData from "../icons/fit-width";
import FitPageIconData from "../icons/fit-page";
import PrintIconData from "../icons/print";
import ExportIconData from "../icons/export";
import ImportIconData from "../icons/import";
import FolderOpenIconData from "../icons/folder-open";
import SaveAsIconData from "../icons/save-as";
import ReplaceIconData from "../icons/replace";
import SpellCheckIconData from "../icons/spell-check";
import WordCountIconData from "../icons/word-count";
import TrackChangesIconData from "../icons/track-changes";
import AcceptChangeIconData from "../icons/accept-change";
import RejectChangeIconData from "../icons/reject-change";
import HistoryIconData from "../icons/history";
import SignatureIconData from "../icons/signature";
import RotatePageIconData from "../icons/rotate-page";
import InsertPageIconData from "../icons/insert-page";
import DeletePageIconData from "../icons/delete-page";
import ExtractPagesIconData from "../icons/extract-pages";
import MergeFilesIconData from "../icons/merge-files";
import SplitFileIconData from "../icons/split-file";
import PageThumbnailsIconData from "../icons/page-thumbnails";
import AnnotateUnderlineIconData from "../icons/annotate-underline";
import AnnotateStrikeoutIconData from "../icons/annotate-strikeout";
import StickyNoteIconData from "../icons/sticky-note";
import DrawIconData from "../icons/draw";
import AnnotateTextIconData from "../icons/annotate-text";
import StampIconData from "../icons/stamp";
import RedactIconData from "../icons/redact";
import FormTextFieldIconData from "../icons/form-text-field";
import FormCheckboxIconData from "../icons/form-checkbox";
import FormRadioIconData from "../icons/form-radio";
import FormDropdownIconData from "../icons/form-dropdown";
import ScanTextIconData from "../icons/scan-text";
import CompareIconData from "../icons/compare";
import DocumentOutlineIconData from "../icons/document-outline";
import PageFirstIconData from "../icons/page-first";
import PageLastIconData from "../icons/page-last";
import MeasureIconData from "../icons/measure";
import BorderAllIconData from "../icons/border-all";
import BorderOuterIconData from "../icons/border-outer";
import BorderInnerIconData from "../icons/border-inner";
import BorderTopIconData from "../icons/border-top";
import BorderBottomIconData from "../icons/border-bottom";
import BorderLeftIconData from "../icons/border-left";
import BorderRightIconData from "../icons/border-right";
import BorderNoneIconData from "../icons/border-none";
import MergeCellsIconData from "../icons/merge-cells";
import SplitCellsIconData from "../icons/split-cells";
import VerticalAlignTopIconData from "../icons/vertical-align-top";
import VerticalAlignMiddleIconData from "../icons/vertical-align-middle";
import VerticalAlignBottomIconData from "../icons/vertical-align-bottom";
import TextRotateIconData from "../icons/text-rotate";
import FillColorIconData from "../icons/fill-color";
import CurrencyIconData from "../icons/currency";
import PercentIconData from "../icons/percent";
import DecimalIncreaseIconData from "../icons/decimal-increase";
import DecimalDecreaseIconData from "../icons/decimal-decrease";
import NumberFormatIconData from "../icons/number-format";
import InsertRowAboveIconData from "../icons/insert-row-above";
import InsertRowBelowIconData from "../icons/insert-row-below";
import InsertColumnLeftIconData from "../icons/insert-column-left";
import InsertColumnRightIconData from "../icons/insert-column-right";
import DeleteRowIconData from "../icons/delete-row";
import DeleteColumnIconData from "../icons/delete-column";
import FreezePanesIconData from "../icons/freeze-panes";
import RowHeightIconData from "../icons/row-height";
import ColumnWidthIconData from "../icons/column-width";
import SortAscendingIconData from "../icons/sort-ascending";
import SortDescendingIconData from "../icons/sort-descending";
import FilterIconData from "../icons/filter";
import FilterOffIconData from "../icons/filter-off";
import GroupRowsIconData from "../icons/group-rows";
import DataValidationIconData from "../icons/data-validation";
import RemoveDuplicatesIconData from "../icons/remove-duplicates";
import TextToColumnsIconData from "../icons/text-to-columns";
import PivotTableIconData from "../icons/pivot-table";
import FunctionIconData from "../icons/function";
import SumIconData from "../icons/sum";
import ConditionalFormatIconData from "../icons/conditional-format";
import NamedRangeIconData from "../icons/named-range";
import InsertSheetIconData from "../icons/insert-sheet";
import GridlinesIconData from "../icons/gridlines";
import ChartBarIconData from "../icons/chart-bar";
import ChartColumnIconData from "../icons/chart-column";
import ChartLineIconData from "../icons/chart-line";
import ChartAreaIconData from "../icons/chart-area";
import ChartPieIconData from "../icons/chart-pie";
import ChartDoughnutIconData from "../icons/chart-doughnut";
import ChartScatterIconData from "../icons/chart-scatter";
import ChartRadarIconData from "../icons/chart-radar";
import ChartComboIconData from "../icons/chart-combo";
import SparklineIconData from "../icons/sparkline";
import NewSlideIconData from "../icons/new-slide";
import SlideLayoutIconData from "../icons/slide-layout";
import ThemeIconData from "../icons/theme";
import SlideBackgroundIconData from "../icons/slide-background";
import TransitionIconData from "../icons/transition";
import AnimationIconData from "../icons/animation";
import PresentIconData from "../icons/present";
import PresentFromStartIconData from "../icons/present-from-start";
import PresenterViewIconData from "../icons/presenter-view";
import SlideSorterIconData from "../icons/slide-sorter";
import SpeakerNotesIconData from "../icons/speaker-notes";
import HideSlideIconData from "../icons/hide-slide";
import ShapeRectangleIconData from "../icons/shape-rectangle";
import ShapeEllipseIconData from "../icons/shape-ellipse";
import ShapeTriangleIconData from "../icons/shape-triangle";
import ShapeArrowIconData from "../icons/shape-arrow";
import ShapeStarIconData from "../icons/shape-star";
import ShapeLineIconData from "../icons/shape-line";
import ConnectorIconData from "../icons/connector";
import BringForwardIconData from "../icons/bring-forward";
import SendBackwardIconData from "../icons/send-backward";
import BringToFrontIconData from "../icons/bring-to-front";
import SendToBackIconData from "../icons/send-to-back";
import GroupIconData from "../icons/group";
import UngroupIconData from "../icons/ungroup";
import AlignObjectsLeftIconData from "../icons/align-objects-left";
import AlignObjectsCenterIconData from "../icons/align-objects-center";
import AlignObjectsRightIconData from "../icons/align-objects-right";
import AlignObjectsTopIconData from "../icons/align-objects-top";
import AlignObjectsMiddleIconData from "../icons/align-objects-middle";
import AlignObjectsBottomIconData from "../icons/align-objects-bottom";
import DistributeHorizontalIconData from "../icons/distribute-horizontal";
import DistributeVerticalIconData from "../icons/distribute-vertical";
import FlipHorizontalIconData from "../icons/flip-horizontal";
import FlipVerticalIconData from "../icons/flip-vertical";
import CropIconData from "../icons/crop";
import RotateObjectIconData from "../icons/rotate-object";
import LaserPointerIconData from "../icons/laser-pointer";
import ShapeOutlineIconData from "../icons/shape-outline";
import ShapeFillIconData from "../icons/shape-fill";
import SuperscriptIconData from "../icons/superscript";
import SubscriptIconData from "../icons/subscript";
import FontColorIconData from "../icons/font-color";
import HighlighterIconData from "../icons/highlighter";
import ClearFormattingIconData from "../icons/clear-formatting";
import FontSizeIncreaseIconData from "../icons/font-size-increase";
import FontSizeDecreaseIconData from "../icons/font-size-decrease";
import ChangeCaseIconData from "../icons/change-case";
import LetterSpacingIconData from "../icons/letter-spacing";
import AlignJustifyIconData from "../icons/align-justify";
import IndentIncreaseIconData from "../icons/indent-increase";
import IndentDecreaseIconData from "../icons/indent-decrease";
import LineSpacingIconData from "../icons/line-spacing";
import ParagraphSpacingIconData from "../icons/paragraph-spacing";
import PilcrowIconData from "../icons/pilcrow";
import ListChecksIconData from "../icons/list-checks";
import ListNestedIconData from "../icons/list-nested";
import Heading1IconData from "../icons/heading1";
import Heading3IconData from "../icons/heading3";
import CodeBlockIconData from "../icons/code-block";
import HorizontalRuleIconData from "../icons/horizontal-rule";
import FormatPainterIconData from "../icons/format-painter";

export const ChevronRightIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronRightIconData);
export const ChevronIcon: IconComponent = ChevronRightIcon;
export const PathStepIcon: IconComponent = ChevronRightIcon;
export const ChevronLeftIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronLeftIconData);
export const ChevronDownIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronDownIconData);
export const DisclosureIcon: IconComponent = ChevronDownIcon;
export const ChevronUpIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronUpIconData);
export const ArrowRightIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowRightIconData);
export const ArrowRight: IconComponent = ArrowRightIcon;
export const ArrowLeftIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowLeftIconData);
export const ArrowLeft: IconComponent = ArrowLeftIcon;
export const ArrowDownIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowDownIconData);
export const SortDownIcon: IconComponent = ArrowDownIcon;
export const ArrowUpIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowUpIconData);
export const SortUpIcon: IconComponent = ArrowUpIcon;
export const CheckIcon: IconComponent = /* @__PURE__ */ createIcon(CheckIconData);
export const Check: IconComponent = CheckIcon;
export const XIcon: IconComponent = /* @__PURE__ */ createIcon(XIconData);
export const CloseIcon: IconComponent = XIcon;
export const X: IconComponent = XIcon;
export const PlusIcon: IconComponent = /* @__PURE__ */ createIcon(PlusIconData);
export const MinusIcon: IconComponent = /* @__PURE__ */ createIcon(MinusIconData);
export const MenuIcon: IconComponent = /* @__PURE__ */ createIcon(MenuIconData);
export const EllipsisIcon: IconComponent = /* @__PURE__ */ createIcon(EllipsisIconData);
export const SpinnerIcon: IconComponent = /* @__PURE__ */ createIcon(SpinnerIconData);
export const Loader2: IconComponent = SpinnerIcon;
export const Loader2Icon: IconComponent = SpinnerIcon;
export const SquareIcon: IconComponent = /* @__PURE__ */ createIcon(SquareIconData);
export const SearchIcon: IconComponent = /* @__PURE__ */ createIcon(SearchIconData);
export const ExternalIcon: IconComponent = /* @__PURE__ */ createIcon(ExternalIconData);
export const CopyIcon: IconComponent = /* @__PURE__ */ createIcon(CopyIconData);
export const TrashIcon: IconComponent = /* @__PURE__ */ createIcon(TrashIconData);
export const Trash2Icon: IconComponent = TrashIcon;
export const DownloadIcon: IconComponent = /* @__PURE__ */ createIcon(DownloadIconData);
export const UploadIcon: IconComponent = /* @__PURE__ */ createIcon(UploadIconData);
export const ExternalLinkIcon: IconComponent = /* @__PURE__ */ createIcon(ExternalLinkIconData);
export const ExternalLink: IconComponent = ExternalLinkIcon;
export const PencilIcon: IconComponent = /* @__PURE__ */ createIcon(PencilIconData);
export const SaveIcon: IconComponent = /* @__PURE__ */ createIcon(SaveIconData);
export const EraserIcon: IconComponent = /* @__PURE__ */ createIcon(EraserIconData);
export const RefreshCwIcon: IconComponent = /* @__PURE__ */ createIcon(RefreshCwIconData);
export const RotateCcwIcon: IconComponent = /* @__PURE__ */ createIcon(RotateCcwIconData);
export const AgainIcon: IconComponent = RotateCcwIcon;
export const RotateCwIcon: IconComponent = /* @__PURE__ */ createIcon(RotateCwIconData);
export const RotateCw: IconComponent = RotateCwIcon;
export const Undo2Icon: IconComponent = /* @__PURE__ */ createIcon(Undo2IconData);
export const Redo2Icon: IconComponent = /* @__PURE__ */ createIcon(Redo2IconData);
export const ScissorsIcon: IconComponent = /* @__PURE__ */ createIcon(ScissorsIconData);
export const ClipboardIcon: IconComponent = /* @__PURE__ */ createIcon(ClipboardIconData);
export const ClipboardPasteIcon: IconComponent = /* @__PURE__ */ createIcon(ClipboardPasteIconData);
export const PinIcon: IconComponent = /* @__PURE__ */ createIcon(PinIconData);
export const FoldVerticalIcon: IconComponent = /* @__PURE__ */ createIcon(FoldVerticalIconData);
export const WrapTextIcon: IconComponent = /* @__PURE__ */ createIcon(WrapTextIconData);
export const LinkIcon: IconComponent = /* @__PURE__ */ createIcon(LinkIconData);
export const Link2Icon: IconComponent = LinkIcon;
export const PaperclipIcon: IconComponent = /* @__PURE__ */ createIcon(PaperclipIconData);
export const LogOutIcon: IconComponent = /* @__PURE__ */ createIcon(LogOutIconData);
export const MaximizeIcon: IconComponent = /* @__PURE__ */ createIcon(MaximizeIconData);
export const Maximize2: IconComponent = MaximizeIcon;
export const MinimizeIcon: IconComponent = /* @__PURE__ */ createIcon(MinimizeIconData);
export const Minimize2: IconComponent = MinimizeIcon;
export const PanelLeftCloseIcon: IconComponent = /* @__PURE__ */ createIcon(PanelLeftCloseIconData);
export const PanelLeftOpenIcon: IconComponent = /* @__PURE__ */ createIcon(PanelLeftOpenIconData);
export const SquareArrowOutUpRightIcon: IconComponent = /* @__PURE__ */ createIcon(SquareArrowOutUpRightIconData);
export const TriangleAlertIcon: IconComponent = /* @__PURE__ */ createIcon(TriangleAlertIconData);
export const WarnIcon: IconComponent = TriangleAlertIcon;
export const InfoIcon: IconComponent = /* @__PURE__ */ createIcon(InfoIconData);
export const CircleCheckIcon: IconComponent = /* @__PURE__ */ createIcon(CircleCheckIconData);
export const OctagonXIcon: IconComponent = /* @__PURE__ */ createIcon(OctagonXIconData);
export const BanIcon: IconComponent = /* @__PURE__ */ createIcon(BanIconData);
export const LockIcon: IconComponent = /* @__PURE__ */ createIcon(LockIconData);
export const LockedIcon: IconComponent = LockIcon;
export const KeyRoundIcon: IconComponent = /* @__PURE__ */ createIcon(KeyRoundIconData);
export const ShieldIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldIconData);
export const ShieldAlertIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldAlertIconData);
export const ShieldPlusIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldPlusIconData);
export const SparklesIcon: IconComponent = /* @__PURE__ */ createIcon(SparklesIconData);
export const Sparkles: IconComponent = SparklesIcon;
export const StarIcon: IconComponent = /* @__PURE__ */ createIcon(StarIconData);
export const LightbulbIcon: IconComponent = /* @__PURE__ */ createIcon(LightbulbIconData);
export const Lightbulb: IconComponent = LightbulbIcon;
export const EyeIcon: IconComponent = /* @__PURE__ */ createIcon(EyeIconData);
export const ClockIcon: IconComponent = /* @__PURE__ */ createIcon(ClockIconData);
export const RecentsIcon: IconComponent = ClockIcon;
export const GaugeIcon: IconComponent = /* @__PURE__ */ createIcon(GaugeIconData);
export const GemIcon: IconComponent = /* @__PURE__ */ createIcon(GemIconData);
export const HomeIcon: IconComponent = /* @__PURE__ */ createIcon(HomeIconData);
export const Home: IconComponent = HomeIcon;
export const UserRoundIcon: IconComponent = /* @__PURE__ */ createIcon(UserRoundIconData);
export const UsersIcon: IconComponent = /* @__PURE__ */ createIcon(UsersIconData);
export const MailIcon: IconComponent = /* @__PURE__ */ createIcon(MailIconData);
export const MessageSquareIcon: IconComponent = /* @__PURE__ */ createIcon(MessageSquareIconData);
export const BotIcon: IconComponent = /* @__PURE__ */ createIcon(BotIconData);
export const BugIcon: IconComponent = /* @__PURE__ */ createIcon(BugIconData);
export const BookOpenIcon: IconComponent = /* @__PURE__ */ createIcon(BookOpenIconData);
export const LibraryIcon: IconComponent = /* @__PURE__ */ createIcon(LibraryIconData);
export const CreditCardIcon: IconComponent = /* @__PURE__ */ createIcon(CreditCardIconData);
export const TagIcon: IconComponent = /* @__PURE__ */ createIcon(TagIconData);
export const PackageIcon: IconComponent = /* @__PURE__ */ createIcon(PackageIconData);
export const ArchiveIcon: IconComponent = /* @__PURE__ */ createIcon(ArchiveIconData);
export const MapIcon: IconComponent = /* @__PURE__ */ createIcon(MapIconData);
export const LifeBuoyIcon: IconComponent = /* @__PURE__ */ createIcon(LifeBuoyIconData);
export const WrenchIcon: IconComponent = /* @__PURE__ */ createIcon(WrenchIconData);
export const PlugIcon: IconComponent = /* @__PURE__ */ createIcon(PlugIconData);
export const PlugZapIcon: IconComponent = /* @__PURE__ */ createIcon(PlugZapIconData);
export const ServerIcon: IconComponent = /* @__PURE__ */ createIcon(ServerIconData);
export const CloudIcon: IconComponent = /* @__PURE__ */ createIcon(CloudIconData);
export const GlobeIcon: IconComponent = /* @__PURE__ */ createIcon(GlobeIconData);
export const MonitorIcon: IconComponent = /* @__PURE__ */ createIcon(MonitorIconData);
export const DesktopIcon: IconComponent = MonitorIcon;
export const TabletIcon: IconComponent = /* @__PURE__ */ createIcon(TabletIconData);
export const SmartphoneIcon: IconComponent = /* @__PURE__ */ createIcon(SmartphoneIconData);
export const PhoneIcon: IconComponent = SmartphoneIcon;
export const TerminalIcon: IconComponent = /* @__PURE__ */ createIcon(TerminalIconData);
export const Terminal: IconComponent = TerminalIcon;
export const CodeIcon: IconComponent = /* @__PURE__ */ createIcon(CodeIconData);
export const SettingsIcon: IconComponent = /* @__PURE__ */ createIcon(SettingsIconData);
export const SlidersHorizontalIcon: IconComponent = SettingsIcon;
export const FileTextIcon: IconComponent = /* @__PURE__ */ createIcon(FileTextIconData);
export const FilePlusIcon: IconComponent = /* @__PURE__ */ createIcon(FilePlusIconData);
export const FileMinusIcon: IconComponent = /* @__PURE__ */ createIcon(FileMinusIconData);
export const FilePenIcon: IconComponent = /* @__PURE__ */ createIcon(FilePenIconData);
export const FileSearchIcon: IconComponent = /* @__PURE__ */ createIcon(FileSearchIconData);
export const FileCodeIcon: IconComponent = /* @__PURE__ */ createIcon(FileCodeIconData);
export const FileCode2: IconComponent = FileCodeIcon;
export const FileVideoIcon: IconComponent = /* @__PURE__ */ createIcon(FileVideoIconData);
export const FolderIcon: IconComponent = /* @__PURE__ */ createIcon(FolderIconData);
export const FolderPlusIcon: IconComponent = /* @__PURE__ */ createIcon(FolderPlusIconData);
export const FolderCogIcon: IconComponent = /* @__PURE__ */ createIcon(FolderCogIconData);
export const FoldersIcon: IconComponent = /* @__PURE__ */ createIcon(FoldersIconData);
export const FolderTreeIcon: IconComponent = /* @__PURE__ */ createIcon(FolderTreeIconData);
export const ImageIcon: IconComponent = /* @__PURE__ */ createIcon(ImageIconData);
export const ImagePlayIcon: IconComponent = /* @__PURE__ */ createIcon(ImagePlayIconData);
export const MusicIcon: IconComponent = /* @__PURE__ */ createIcon(MusicIconData);
export const CaptionsIcon: IconComponent = /* @__PURE__ */ createIcon(CaptionsIconData);
export const BoldIcon: IconComponent = /* @__PURE__ */ createIcon(BoldIconData);
export const ItalicIcon: IconComponent = /* @__PURE__ */ createIcon(ItalicIconData);
export const UnderlineIcon: IconComponent = /* @__PURE__ */ createIcon(UnderlineIconData);
export const StrikethroughIcon: IconComponent = /* @__PURE__ */ createIcon(StrikethroughIconData);
export const Heading2Icon: IconComponent = /* @__PURE__ */ createIcon(Heading2IconData);
export const QuoteIcon: IconComponent = /* @__PURE__ */ createIcon(QuoteIconData);
export const ListIcon: IconComponent = /* @__PURE__ */ createIcon(ListIconData);
export const ListOrderedIcon: IconComponent = /* @__PURE__ */ createIcon(ListOrderedIconData);
export const CodeAppIcon: IconComponent = /* @__PURE__ */ createIcon(CodeAppIconData);
export const FinderAppIcon: IconComponent = /* @__PURE__ */ createIcon(FinderAppIconData);
export const MediaAppIcon: IconComponent = /* @__PURE__ */ createIcon(MediaAppIconData);
export const PageAppIcon: IconComponent = /* @__PURE__ */ createIcon(PageAppIconData);
export const PortfolioAppIcon: IconComponent = /* @__PURE__ */ createIcon(PortfolioAppIconData);
export const CvAppIcon: IconComponent = /* @__PURE__ */ createIcon(CvAppIconData);
export const HelpAppIcon: IconComponent = /* @__PURE__ */ createIcon(HelpAppIconData);
export const SupportAppIcon: IconComponent = /* @__PURE__ */ createIcon(SupportAppIconData);
export const StoryAppIcon: IconComponent = /* @__PURE__ */ createIcon(StoryAppIconData);
export const CoursesAppIcon: IconComponent = /* @__PURE__ */ createIcon(CoursesAppIconData);
export const TermsAppIcon: IconComponent = /* @__PURE__ */ createIcon(TermsAppIconData);
export const PrivacyAppIcon: IconComponent = /* @__PURE__ */ createIcon(PrivacyAppIconData);
export const AcceptableUseAppIcon: IconComponent = /* @__PURE__ */ createIcon(AcceptableUseAppIconData);
export const CookiesAppIcon: IconComponent = /* @__PURE__ */ createIcon(CookiesAppIconData);
export const RefundsAppIcon: IconComponent = /* @__PURE__ */ createIcon(RefundsAppIconData);
export const AppsIcon: IconComponent = /* @__PURE__ */ createIcon(AppsIconData);
export const VideoGroupIcon: IconComponent = /* @__PURE__ */ createIcon(VideoGroupIconData);
export const VideosKindIcon: IconComponent = VideoGroupIcon;
export const ImageGroupIcon: IconComponent = /* @__PURE__ */ createIcon(ImageGroupIconData);
export const ImagesKindIcon: IconComponent = ImageGroupIcon;
export const AudioGroupIcon: IconComponent = /* @__PURE__ */ createIcon(AudioGroupIconData);
export const AudioKindIcon: IconComponent = AudioGroupIcon;
export const PdfGroupIcon: IconComponent = /* @__PURE__ */ createIcon(PdfGroupIconData);
export const DocumentsKindIcon: IconComponent = PdfGroupIcon;
export const AnimateGroupIcon: IconComponent = /* @__PURE__ */ createIcon(AnimateGroupIconData);
export const SubtitleGroupIcon: IconComponent = /* @__PURE__ */ createIcon(SubtitleGroupIconData);
export const QueueIcon: IconComponent = /* @__PURE__ */ createIcon(QueueIconData);
export const ProIcon: IconComponent = /* @__PURE__ */ createIcon(ProIconData);
export const VideoShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(VideoShrinkIconData);
export const FitSizeIcon: IconComponent = /* @__PURE__ */ createIcon(FitSizeIconData);
export const TrimIcon: IconComponent = /* @__PURE__ */ createIcon(TrimIconData);
export const ConvertIcon: IconComponent = /* @__PURE__ */ createIcon(ConvertIconData);
export const VideoToGifIcon: IconComponent = /* @__PURE__ */ createIcon(VideoToGifIconData);
export const ResizeIcon: IconComponent = /* @__PURE__ */ createIcon(ResizeIconData);
export const MuteIcon: IconComponent = /* @__PURE__ */ createIcon(MuteIconData);
export const ImageShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(ImageShrinkIconData);
export const LongestEdgeIcon: IconComponent = /* @__PURE__ */ createIcon(LongestEdgeIconData);
export const StripDataIcon: IconComponent = /* @__PURE__ */ createIcon(StripDataIconData);
export const AudioShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(AudioShrinkIconData);
export const VoiceIcon: IconComponent = /* @__PURE__ */ createIcon(VoiceIconData);
export const PdfShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(PdfShrinkIconData);
export const GrayscaleIcon: IconComponent = /* @__PURE__ */ createIcon(GrayscaleIconData);
export const MakeAnimationIcon: IconComponent = /* @__PURE__ */ createIcon(MakeAnimationIconData);
export const WriteSubtitlesIcon: IconComponent = /* @__PURE__ */ createIcon(WriteSubtitlesIconData);
export const TranscribeIcon: IconComponent = /* @__PURE__ */ createIcon(TranscribeIconData);
export const BurnInIcon: IconComponent = /* @__PURE__ */ createIcon(BurnInIconData);
export const SubtitleTrackIcon: IconComponent = /* @__PURE__ */ createIcon(SubtitleTrackIconData);
export const ToolsIcon: IconComponent = /* @__PURE__ */ createIcon(ToolsIconData);
export const PlayIcon: IconComponent = /* @__PURE__ */ createIcon(PlayIconData);
export const PauseIcon: IconComponent = /* @__PURE__ */ createIcon(PauseIconData);
export const NewIcon: IconComponent = /* @__PURE__ */ createIcon(NewIconData);
export const ProjectsIcon: IconComponent = /* @__PURE__ */ createIcon(ProjectsIconData);
export const FilesIcon: IconComponent = /* @__PURE__ */ createIcon(FilesIconData);
export const AgentIcon: IconComponent = /* @__PURE__ */ createIcon(AgentIconData);
export const PackagesIcon: IconComponent = /* @__PURE__ */ createIcon(PackagesIconData);
export const ShareIcon: IconComponent = /* @__PURE__ */ createIcon(ShareIconData);
export const AllFilesIcon: IconComponent = /* @__PURE__ */ createIcon(AllFilesIconData);
export const PublicIcon: IconComponent = /* @__PURE__ */ createIcon(PublicIconData);
export const IconsViewIcon: IconComponent = /* @__PURE__ */ createIcon(IconsViewIconData);
export const ListViewIcon: IconComponent = /* @__PURE__ */ createIcon(ListViewIconData);
export const ColumnsViewIcon: IconComponent = /* @__PURE__ */ createIcon(ColumnsViewIconData);
export const GalleryViewIcon: IconComponent = /* @__PURE__ */ createIcon(GalleryViewIconData);
export const SmallTilesIcon: IconComponent = /* @__PURE__ */ createIcon(SmallTilesIconData);
export const LargeTilesIcon: IconComponent = /* @__PURE__ */ createIcon(LargeTilesIconData);
export const CommandKeyIcon: IconComponent = /* @__PURE__ */ createIcon(CommandKeyIconData);
export const ShiftKeyIcon: IconComponent = /* @__PURE__ */ createIcon(ShiftKeyIconData);
export const LayersIcon: IconComponent = /* @__PURE__ */ createIcon(LayersIconData);
export const BlocksIcon: IconComponent = /* @__PURE__ */ createIcon(BlocksIconData);
export const GripIcon: IconComponent = /* @__PURE__ */ createIcon(GripIconData);
export const EyeOffIcon: IconComponent = /* @__PURE__ */ createIcon(EyeOffIconData);
export const UnlockIcon: IconComponent = /* @__PURE__ */ createIcon(UnlockIconData);
export const DuplicateIcon: IconComponent = /* @__PURE__ */ createIcon(DuplicateIconData);
export const AlignLeftIcon: IconComponent = /* @__PURE__ */ createIcon(AlignLeftIconData);
export const AlignCenterIcon: IconComponent = /* @__PURE__ */ createIcon(AlignCenterIconData);
export const AlignRightIcon: IconComponent = /* @__PURE__ */ createIcon(AlignRightIconData);
export const PanIcon: IconComponent = /* @__PURE__ */ createIcon(PanIconData);
export const FitScreenIcon: IconComponent = /* @__PURE__ */ createIcon(FitScreenIconData);
export const PageBreakIcon: IconComponent = /* @__PURE__ */ createIcon(PageBreakIconData);
export const PublishIcon: IconComponent = /* @__PURE__ */ createIcon(PublishIconData);
export const TemplateIcon: IconComponent = /* @__PURE__ */ createIcon(TemplateIconData);
export const VersionsIcon: IconComponent = /* @__PURE__ */ createIcon(VersionsIconData);
export const SectionIcon: IconComponent = /* @__PURE__ */ createIcon(SectionIconData);
export const TextIcon: IconComponent = /* @__PURE__ */ createIcon(TextIconData);
export const TypeIcon: IconComponent = TextIcon;
export const FormIcon: IconComponent = /* @__PURE__ */ createIcon(FormIconData);
export const SpreadsheetIcon: IconComponent = /* @__PURE__ */ createIcon(SpreadsheetIconData);
export const PresentationIcon: IconComponent = /* @__PURE__ */ createIcon(PresentationIconData);
export const RunSnipMark: IconComponent = /* @__PURE__ */ createIcon(RunSnipMarkData);
export const RunSnipWordmark: IconComponent = /* @__PURE__ */ createIcon(RunSnipWordmarkData);
export const IconGoogle: IconComponent = /* @__PURE__ */ createIcon(IconGoogleData);
export const IconGithub: IconComponent = /* @__PURE__ */ createIcon(IconGithubData);
export const CommentAddIcon: IconComponent = /* @__PURE__ */ createIcon(CommentAddIconData);
export const CommentsIcon: IconComponent = /* @__PURE__ */ createIcon(CommentsIconData);
export const ReplyIcon: IconComponent = /* @__PURE__ */ createIcon(ReplyIconData);
export const ReplyAllIcon: IconComponent = /* @__PURE__ */ createIcon(ReplyAllIconData);
export const ReopenIcon: IconComponent = /* @__PURE__ */ createIcon(ReopenIconData);
export const AtSignIcon: IconComponent = /* @__PURE__ */ createIcon(AtSignIconData);
export const BellIcon: IconComponent = /* @__PURE__ */ createIcon(BellIconData);
export const BellOffIcon: IconComponent = /* @__PURE__ */ createIcon(BellOffIconData);
export const CursorIcon: IconComponent = /* @__PURE__ */ createIcon(CursorIconData);
export const HandIcon: IconComponent = /* @__PURE__ */ createIcon(HandIconData);
export const FollowIcon: IconComponent = /* @__PURE__ */ createIcon(FollowIconData);
export const PresenceIcon: IconComponent = /* @__PURE__ */ createIcon(PresenceIconData);
export const MoreVerticalIcon: IconComponent = /* @__PURE__ */ createIcon(MoreVerticalIconData);
export const ChevronsUpDownIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronsUpDownIconData);
export const ChevronsLeftIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronsLeftIconData);
export const ChevronsRightIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronsRightIconData);
export const ExpandIcon: IconComponent = /* @__PURE__ */ createIcon(ExpandIconData);
export const CollapseIcon: IconComponent = /* @__PURE__ */ createIcon(CollapseIconData);
export const SunIcon: IconComponent = /* @__PURE__ */ createIcon(SunIconData);
export const MoonIcon: IconComponent = /* @__PURE__ */ createIcon(MoonIconData);
export const HelpCircleIcon: IconComponent = /* @__PURE__ */ createIcon(HelpCircleIconData);
export const ThumbsUpIcon: IconComponent = /* @__PURE__ */ createIcon(ThumbsUpIconData);
export const PaletteIcon: IconComponent = /* @__PURE__ */ createIcon(PaletteIconData);
export const DropletIcon: IconComponent = /* @__PURE__ */ createIcon(DropletIconData);
export const MicIcon: IconComponent = /* @__PURE__ */ createIcon(MicIconData);
export const MicOffIcon: IconComponent = /* @__PURE__ */ createIcon(MicOffIconData);
export const KeyboardIcon: IconComponent = /* @__PURE__ */ createIcon(KeyboardIconData);
export const TranslateIcon: IconComponent = /* @__PURE__ */ createIcon(TranslateIconData);
export const SendIcon: IconComponent = /* @__PURE__ */ createIcon(SendIconData);
export const InboxIcon: IconComponent = /* @__PURE__ */ createIcon(InboxIconData);
export const ActivityIcon: IconComponent = /* @__PURE__ */ createIcon(ActivityIconData);
export const PanelRightOpenIcon: IconComponent = /* @__PURE__ */ createIcon(PanelRightOpenIconData);
export const PanelRightCloseIcon: IconComponent = /* @__PURE__ */ createIcon(PanelRightCloseIconData);
export const LayoutGridIcon: IconComponent = /* @__PURE__ */ createIcon(LayoutGridIconData);
export const SortIcon: IconComponent = /* @__PURE__ */ createIcon(SortIconData);
export const LassoIcon: IconComponent = /* @__PURE__ */ createIcon(LassoIconData);
export const TableIcon: IconComponent = /* @__PURE__ */ createIcon(TableIconData);
export const ShapesIcon: IconComponent = /* @__PURE__ */ createIcon(ShapesIconData);
export const TextBoxIcon: IconComponent = /* @__PURE__ */ createIcon(TextBoxIconData);
export const EquationIcon: IconComponent = /* @__PURE__ */ createIcon(EquationIconData);
export const SymbolIcon: IconComponent = /* @__PURE__ */ createIcon(SymbolIconData);
export const EmojiIcon: IconComponent = /* @__PURE__ */ createIcon(EmojiIconData);
export const CalendarIcon: IconComponent = /* @__PURE__ */ createIcon(CalendarIconData);
export const DateTimeIcon: IconComponent = /* @__PURE__ */ createIcon(DateTimeIconData);
export const HeaderIcon: IconComponent = /* @__PURE__ */ createIcon(HeaderIconData);
export const FooterIcon: IconComponent = /* @__PURE__ */ createIcon(FooterIconData);
export const PageNumberIcon: IconComponent = /* @__PURE__ */ createIcon(PageNumberIconData);
export const FootnoteIcon: IconComponent = /* @__PURE__ */ createIcon(FootnoteIconData);
export const BookmarkIcon: IconComponent = /* @__PURE__ */ createIcon(BookmarkIconData);
export const TableOfContentsIcon: IconComponent = /* @__PURE__ */ createIcon(TableOfContentsIconData);
export const UnlinkIcon: IconComponent = /* @__PURE__ */ createIcon(UnlinkIconData);
export const ImagePlusIcon: IconComponent = /* @__PURE__ */ createIcon(ImagePlusIconData);
export const WatermarkIcon: IconComponent = /* @__PURE__ */ createIcon(WatermarkIconData);
export const SectionBreakIcon: IconComponent = /* @__PURE__ */ createIcon(SectionBreakIconData);
export const PortraitPageIcon: IconComponent = /* @__PURE__ */ createIcon(PortraitPageIconData);
export const LandscapePageIcon: IconComponent = /* @__PURE__ */ createIcon(LandscapePageIconData);
export const MarginsIcon: IconComponent = /* @__PURE__ */ createIcon(MarginsIconData);
export const PageSizeIcon: IconComponent = /* @__PURE__ */ createIcon(PageSizeIconData);
export const RulerIcon: IconComponent = /* @__PURE__ */ createIcon(RulerIconData);
export const ZoomInIcon: IconComponent = /* @__PURE__ */ createIcon(ZoomInIconData);
export const ZoomOutIcon: IconComponent = /* @__PURE__ */ createIcon(ZoomOutIconData);
export const FitWidthIcon: IconComponent = /* @__PURE__ */ createIcon(FitWidthIconData);
export const FitPageIcon: IconComponent = /* @__PURE__ */ createIcon(FitPageIconData);
export const PrintIcon: IconComponent = /* @__PURE__ */ createIcon(PrintIconData);
export const ExportIcon: IconComponent = /* @__PURE__ */ createIcon(ExportIconData);
export const ImportIcon: IconComponent = /* @__PURE__ */ createIcon(ImportIconData);
export const FolderOpenIcon: IconComponent = /* @__PURE__ */ createIcon(FolderOpenIconData);
export const SaveAsIcon: IconComponent = /* @__PURE__ */ createIcon(SaveAsIconData);
export const ReplaceIcon: IconComponent = /* @__PURE__ */ createIcon(ReplaceIconData);
export const SpellCheckIcon: IconComponent = /* @__PURE__ */ createIcon(SpellCheckIconData);
export const WordCountIcon: IconComponent = /* @__PURE__ */ createIcon(WordCountIconData);
export const TrackChangesIcon: IconComponent = /* @__PURE__ */ createIcon(TrackChangesIconData);
export const AcceptChangeIcon: IconComponent = /* @__PURE__ */ createIcon(AcceptChangeIconData);
export const RejectChangeIcon: IconComponent = /* @__PURE__ */ createIcon(RejectChangeIconData);
export const HistoryIcon: IconComponent = /* @__PURE__ */ createIcon(HistoryIconData);
export const SignatureIcon: IconComponent = /* @__PURE__ */ createIcon(SignatureIconData);
export const RotatePageIcon: IconComponent = /* @__PURE__ */ createIcon(RotatePageIconData);
export const InsertPageIcon: IconComponent = /* @__PURE__ */ createIcon(InsertPageIconData);
export const DeletePageIcon: IconComponent = /* @__PURE__ */ createIcon(DeletePageIconData);
export const ExtractPagesIcon: IconComponent = /* @__PURE__ */ createIcon(ExtractPagesIconData);
export const MergeFilesIcon: IconComponent = /* @__PURE__ */ createIcon(MergeFilesIconData);
export const SplitFileIcon: IconComponent = /* @__PURE__ */ createIcon(SplitFileIconData);
export const PageThumbnailsIcon: IconComponent = /* @__PURE__ */ createIcon(PageThumbnailsIconData);
export const AnnotateUnderlineIcon: IconComponent = /* @__PURE__ */ createIcon(AnnotateUnderlineIconData);
export const AnnotateStrikeoutIcon: IconComponent = /* @__PURE__ */ createIcon(AnnotateStrikeoutIconData);
export const StickyNoteIcon: IconComponent = /* @__PURE__ */ createIcon(StickyNoteIconData);
export const DrawIcon: IconComponent = /* @__PURE__ */ createIcon(DrawIconData);
export const AnnotateTextIcon: IconComponent = /* @__PURE__ */ createIcon(AnnotateTextIconData);
export const StampIcon: IconComponent = /* @__PURE__ */ createIcon(StampIconData);
export const RedactIcon: IconComponent = /* @__PURE__ */ createIcon(RedactIconData);
export const FormTextFieldIcon: IconComponent = /* @__PURE__ */ createIcon(FormTextFieldIconData);
export const FormCheckboxIcon: IconComponent = /* @__PURE__ */ createIcon(FormCheckboxIconData);
export const FormRadioIcon: IconComponent = /* @__PURE__ */ createIcon(FormRadioIconData);
export const FormDropdownIcon: IconComponent = /* @__PURE__ */ createIcon(FormDropdownIconData);
export const ScanTextIcon: IconComponent = /* @__PURE__ */ createIcon(ScanTextIconData);
export const CompareIcon: IconComponent = /* @__PURE__ */ createIcon(CompareIconData);
export const DocumentOutlineIcon: IconComponent = /* @__PURE__ */ createIcon(DocumentOutlineIconData);
export const PageFirstIcon: IconComponent = /* @__PURE__ */ createIcon(PageFirstIconData);
export const PageLastIcon: IconComponent = /* @__PURE__ */ createIcon(PageLastIconData);
export const MeasureIcon: IconComponent = /* @__PURE__ */ createIcon(MeasureIconData);
export const BorderAllIcon: IconComponent = /* @__PURE__ */ createIcon(BorderAllIconData);
export const BorderOuterIcon: IconComponent = /* @__PURE__ */ createIcon(BorderOuterIconData);
export const BorderInnerIcon: IconComponent = /* @__PURE__ */ createIcon(BorderInnerIconData);
export const BorderTopIcon: IconComponent = /* @__PURE__ */ createIcon(BorderTopIconData);
export const BorderBottomIcon: IconComponent = /* @__PURE__ */ createIcon(BorderBottomIconData);
export const BorderLeftIcon: IconComponent = /* @__PURE__ */ createIcon(BorderLeftIconData);
export const BorderRightIcon: IconComponent = /* @__PURE__ */ createIcon(BorderRightIconData);
export const BorderNoneIcon: IconComponent = /* @__PURE__ */ createIcon(BorderNoneIconData);
export const MergeCellsIcon: IconComponent = /* @__PURE__ */ createIcon(MergeCellsIconData);
export const SplitCellsIcon: IconComponent = /* @__PURE__ */ createIcon(SplitCellsIconData);
export const VerticalAlignTopIcon: IconComponent = /* @__PURE__ */ createIcon(VerticalAlignTopIconData);
export const VerticalAlignMiddleIcon: IconComponent = /* @__PURE__ */ createIcon(VerticalAlignMiddleIconData);
export const VerticalAlignBottomIcon: IconComponent = /* @__PURE__ */ createIcon(VerticalAlignBottomIconData);
export const TextRotateIcon: IconComponent = /* @__PURE__ */ createIcon(TextRotateIconData);
export const FillColorIcon: IconComponent = /* @__PURE__ */ createIcon(FillColorIconData);
export const CurrencyIcon: IconComponent = /* @__PURE__ */ createIcon(CurrencyIconData);
export const PercentIcon: IconComponent = /* @__PURE__ */ createIcon(PercentIconData);
export const DecimalIncreaseIcon: IconComponent = /* @__PURE__ */ createIcon(DecimalIncreaseIconData);
export const DecimalDecreaseIcon: IconComponent = /* @__PURE__ */ createIcon(DecimalDecreaseIconData);
export const NumberFormatIcon: IconComponent = /* @__PURE__ */ createIcon(NumberFormatIconData);
export const InsertRowAboveIcon: IconComponent = /* @__PURE__ */ createIcon(InsertRowAboveIconData);
export const InsertRowBelowIcon: IconComponent = /* @__PURE__ */ createIcon(InsertRowBelowIconData);
export const InsertColumnLeftIcon: IconComponent = /* @__PURE__ */ createIcon(InsertColumnLeftIconData);
export const InsertColumnRightIcon: IconComponent = /* @__PURE__ */ createIcon(InsertColumnRightIconData);
export const DeleteRowIcon: IconComponent = /* @__PURE__ */ createIcon(DeleteRowIconData);
export const DeleteColumnIcon: IconComponent = /* @__PURE__ */ createIcon(DeleteColumnIconData);
export const FreezePanesIcon: IconComponent = /* @__PURE__ */ createIcon(FreezePanesIconData);
export const RowHeightIcon: IconComponent = /* @__PURE__ */ createIcon(RowHeightIconData);
export const ColumnWidthIcon: IconComponent = /* @__PURE__ */ createIcon(ColumnWidthIconData);
export const SortAscendingIcon: IconComponent = /* @__PURE__ */ createIcon(SortAscendingIconData);
export const SortDescendingIcon: IconComponent = /* @__PURE__ */ createIcon(SortDescendingIconData);
export const FilterIcon: IconComponent = /* @__PURE__ */ createIcon(FilterIconData);
export const FilterOffIcon: IconComponent = /* @__PURE__ */ createIcon(FilterOffIconData);
export const GroupRowsIcon: IconComponent = /* @__PURE__ */ createIcon(GroupRowsIconData);
export const DataValidationIcon: IconComponent = /* @__PURE__ */ createIcon(DataValidationIconData);
export const RemoveDuplicatesIcon: IconComponent = /* @__PURE__ */ createIcon(RemoveDuplicatesIconData);
export const TextToColumnsIcon: IconComponent = /* @__PURE__ */ createIcon(TextToColumnsIconData);
export const PivotTableIcon: IconComponent = /* @__PURE__ */ createIcon(PivotTableIconData);
export const FunctionIcon: IconComponent = /* @__PURE__ */ createIcon(FunctionIconData);
export const SumIcon: IconComponent = /* @__PURE__ */ createIcon(SumIconData);
export const ConditionalFormatIcon: IconComponent = /* @__PURE__ */ createIcon(ConditionalFormatIconData);
export const NamedRangeIcon: IconComponent = /* @__PURE__ */ createIcon(NamedRangeIconData);
export const InsertSheetIcon: IconComponent = /* @__PURE__ */ createIcon(InsertSheetIconData);
export const GridlinesIcon: IconComponent = /* @__PURE__ */ createIcon(GridlinesIconData);
export const ChartBarIcon: IconComponent = /* @__PURE__ */ createIcon(ChartBarIconData);
export const ChartColumnIcon: IconComponent = /* @__PURE__ */ createIcon(ChartColumnIconData);
export const ChartLineIcon: IconComponent = /* @__PURE__ */ createIcon(ChartLineIconData);
export const ChartAreaIcon: IconComponent = /* @__PURE__ */ createIcon(ChartAreaIconData);
export const ChartPieIcon: IconComponent = /* @__PURE__ */ createIcon(ChartPieIconData);
export const ChartDoughnutIcon: IconComponent = /* @__PURE__ */ createIcon(ChartDoughnutIconData);
export const ChartScatterIcon: IconComponent = /* @__PURE__ */ createIcon(ChartScatterIconData);
export const ChartRadarIcon: IconComponent = /* @__PURE__ */ createIcon(ChartRadarIconData);
export const ChartComboIcon: IconComponent = /* @__PURE__ */ createIcon(ChartComboIconData);
export const SparklineIcon: IconComponent = /* @__PURE__ */ createIcon(SparklineIconData);
export const NewSlideIcon: IconComponent = /* @__PURE__ */ createIcon(NewSlideIconData);
export const SlideLayoutIcon: IconComponent = /* @__PURE__ */ createIcon(SlideLayoutIconData);
export const ThemeIcon: IconComponent = /* @__PURE__ */ createIcon(ThemeIconData);
export const SlideBackgroundIcon: IconComponent = /* @__PURE__ */ createIcon(SlideBackgroundIconData);
export const TransitionIcon: IconComponent = /* @__PURE__ */ createIcon(TransitionIconData);
export const AnimationIcon: IconComponent = /* @__PURE__ */ createIcon(AnimationIconData);
export const PresentIcon: IconComponent = /* @__PURE__ */ createIcon(PresentIconData);
export const PresentFromStartIcon: IconComponent = /* @__PURE__ */ createIcon(PresentFromStartIconData);
export const PresenterViewIcon: IconComponent = /* @__PURE__ */ createIcon(PresenterViewIconData);
export const SlideSorterIcon: IconComponent = /* @__PURE__ */ createIcon(SlideSorterIconData);
export const SpeakerNotesIcon: IconComponent = /* @__PURE__ */ createIcon(SpeakerNotesIconData);
export const HideSlideIcon: IconComponent = /* @__PURE__ */ createIcon(HideSlideIconData);
export const ShapeRectangleIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeRectangleIconData);
export const ShapeEllipseIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeEllipseIconData);
export const ShapeTriangleIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeTriangleIconData);
export const ShapeArrowIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeArrowIconData);
export const ShapeStarIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeStarIconData);
export const ShapeLineIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeLineIconData);
export const ConnectorIcon: IconComponent = /* @__PURE__ */ createIcon(ConnectorIconData);
export const BringForwardIcon: IconComponent = /* @__PURE__ */ createIcon(BringForwardIconData);
export const SendBackwardIcon: IconComponent = /* @__PURE__ */ createIcon(SendBackwardIconData);
export const BringToFrontIcon: IconComponent = /* @__PURE__ */ createIcon(BringToFrontIconData);
export const SendToBackIcon: IconComponent = /* @__PURE__ */ createIcon(SendToBackIconData);
export const GroupIcon: IconComponent = /* @__PURE__ */ createIcon(GroupIconData);
export const UngroupIcon: IconComponent = /* @__PURE__ */ createIcon(UngroupIconData);
export const AlignObjectsLeftIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsLeftIconData);
export const AlignObjectsCenterIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsCenterIconData);
export const AlignObjectsRightIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsRightIconData);
export const AlignObjectsTopIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsTopIconData);
export const AlignObjectsMiddleIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsMiddleIconData);
export const AlignObjectsBottomIcon: IconComponent = /* @__PURE__ */ createIcon(AlignObjectsBottomIconData);
export const DistributeHorizontalIcon: IconComponent = /* @__PURE__ */ createIcon(DistributeHorizontalIconData);
export const DistributeVerticalIcon: IconComponent = /* @__PURE__ */ createIcon(DistributeVerticalIconData);
export const FlipHorizontalIcon: IconComponent = /* @__PURE__ */ createIcon(FlipHorizontalIconData);
export const FlipVerticalIcon: IconComponent = /* @__PURE__ */ createIcon(FlipVerticalIconData);
export const CropIcon: IconComponent = /* @__PURE__ */ createIcon(CropIconData);
export const RotateObjectIcon: IconComponent = /* @__PURE__ */ createIcon(RotateObjectIconData);
export const LaserPointerIcon: IconComponent = /* @__PURE__ */ createIcon(LaserPointerIconData);
export const ShapeOutlineIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeOutlineIconData);
export const ShapeFillIcon: IconComponent = /* @__PURE__ */ createIcon(ShapeFillIconData);
export const SuperscriptIcon: IconComponent = /* @__PURE__ */ createIcon(SuperscriptIconData);
export const SubscriptIcon: IconComponent = /* @__PURE__ */ createIcon(SubscriptIconData);
export const FontColorIcon: IconComponent = /* @__PURE__ */ createIcon(FontColorIconData);
export const HighlighterIcon: IconComponent = /* @__PURE__ */ createIcon(HighlighterIconData);
export const ClearFormattingIcon: IconComponent = /* @__PURE__ */ createIcon(ClearFormattingIconData);
export const FontSizeIncreaseIcon: IconComponent = /* @__PURE__ */ createIcon(FontSizeIncreaseIconData);
export const FontSizeDecreaseIcon: IconComponent = /* @__PURE__ */ createIcon(FontSizeDecreaseIconData);
export const ChangeCaseIcon: IconComponent = /* @__PURE__ */ createIcon(ChangeCaseIconData);
export const LetterSpacingIcon: IconComponent = /* @__PURE__ */ createIcon(LetterSpacingIconData);
export const AlignJustifyIcon: IconComponent = /* @__PURE__ */ createIcon(AlignJustifyIconData);
export const IndentIncreaseIcon: IconComponent = /* @__PURE__ */ createIcon(IndentIncreaseIconData);
export const IndentDecreaseIcon: IconComponent = /* @__PURE__ */ createIcon(IndentDecreaseIconData);
export const LineSpacingIcon: IconComponent = /* @__PURE__ */ createIcon(LineSpacingIconData);
export const ParagraphSpacingIcon: IconComponent = /* @__PURE__ */ createIcon(ParagraphSpacingIconData);
export const PilcrowIcon: IconComponent = /* @__PURE__ */ createIcon(PilcrowIconData);
export const ListChecksIcon: IconComponent = /* @__PURE__ */ createIcon(ListChecksIconData);
export const ListNestedIcon: IconComponent = /* @__PURE__ */ createIcon(ListNestedIconData);
export const Heading1Icon: IconComponent = /* @__PURE__ */ createIcon(Heading1IconData);
export const Heading3Icon: IconComponent = /* @__PURE__ */ createIcon(Heading3IconData);
export const CodeBlockIcon: IconComponent = /* @__PURE__ */ createIcon(CodeBlockIconData);
export const HorizontalRuleIcon: IconComponent = /* @__PURE__ */ createIcon(HorizontalRuleIconData);
export const FormatPainterIcon: IconComponent = /* @__PURE__ */ createIcon(FormatPainterIconData);
