/* Made by scripts/generate.mjs from icons/*.ts and icons.json. Do not edit; run `npm run generate`. */

import { createIcon, type IconComponent } from "./create";
import ChevronRightIconData from "../icons/chevron-right";
import ChevronLeftIconData from "../icons/chevron-left";
import ChevronDownIconData from "../icons/chevron-down";
import ChevronUpIconData from "../icons/chevron-up";
import ArrowRightIconData from "../icons/arrow-right";
import ArrowLeftIconData from "../icons/arrow-left";
import ArrowDownIconData from "../icons/arrow-down";
import ArrowUpIconData from "../icons/arrow-up";
import CheckIconData from "../icons/check";
import XIconData from "../icons/x";
import PlusIconData from "../icons/plus";
import MinusIconData from "../icons/minus";
import MenuIconData from "../icons/menu";
import EllipsisIconData from "../icons/ellipsis";
import SpinnerIconData from "../icons/spinner";
import SquareIconData from "../icons/square";
import SearchIconData from "../icons/search";
import ExternalIconData from "../icons/external";
import CopyIconData from "../icons/copy";
import TrashIconData from "../icons/trash";
import DownloadIconData from "../icons/download";
import UploadIconData from "../icons/upload";
import ExternalLinkIconData from "../icons/external-link";
import PencilIconData from "../icons/pencil";
import SaveIconData from "../icons/save";
import EraserIconData from "../icons/eraser";
import RefreshCwIconData from "../icons/refresh-cw";
import RotateCcwIconData from "../icons/rotate-ccw";
import RotateCwIconData from "../icons/rotate-cw";
import Undo2IconData from "../icons/undo2";
import Redo2IconData from "../icons/redo2";
import ScissorsIconData from "../icons/scissors";
import ClipboardIconData from "../icons/clipboard";
import ClipboardPasteIconData from "../icons/clipboard-paste";
import PinIconData from "../icons/pin";
import FoldVerticalIconData from "../icons/fold-vertical";
import WrapTextIconData from "../icons/wrap-text";
import LinkIconData from "../icons/link";
import PaperclipIconData from "../icons/paperclip";
import LogOutIconData from "../icons/log-out";
import MaximizeIconData from "../icons/maximize";
import MinimizeIconData from "../icons/minimize";
import PanelLeftCloseIconData from "../icons/panel-left-close";
import PanelLeftOpenIconData from "../icons/panel-left-open";
import SquareArrowOutUpRightIconData from "../icons/square-arrow-out-up-right";
import TriangleAlertIconData from "../icons/triangle-alert";
import InfoIconData from "../icons/info";
import CircleCheckIconData from "../icons/circle-check";
import OctagonXIconData from "../icons/octagon-x";
import BanIconData from "../icons/ban";
import LockIconData from "../icons/lock";
import KeyRoundIconData from "../icons/key-round";
import ShieldIconData from "../icons/shield";
import ShieldAlertIconData from "../icons/shield-alert";
import ShieldPlusIconData from "../icons/shield-plus";
import SparklesIconData from "../icons/sparkles";
import StarIconData from "../icons/star";
import LightbulbIconData from "../icons/lightbulb";
import EyeIconData from "../icons/eye";
import ClockIconData from "../icons/clock";
import GaugeIconData from "../icons/gauge";
import GemIconData from "../icons/gem";
import HomeIconData from "../icons/home";
import UserRoundIconData from "../icons/user-round";
import UsersIconData from "../icons/users";
import MailIconData from "../icons/mail";
import MessageSquareIconData from "../icons/message-square";
import BotIconData from "../icons/bot";
import BugIconData from "../icons/bug";
import BookOpenIconData from "../icons/book-open";
import LibraryIconData from "../icons/library";
import CreditCardIconData from "../icons/credit-card";
import TagIconData from "../icons/tag";
import PackageIconData from "../icons/package";
import ArchiveIconData from "../icons/archive";
import MapIconData from "../icons/map";
import LifeBuoyIconData from "../icons/life-buoy";
import WrenchIconData from "../icons/wrench";
import PlugIconData from "../icons/plug";
import PlugZapIconData from "../icons/plug-zap";
import ServerIconData from "../icons/server";
import CloudIconData from "../icons/cloud";
import GlobeIconData from "../icons/globe";
import MonitorIconData from "../icons/monitor";
import TabletIconData from "../icons/tablet";
import SmartphoneIconData from "../icons/smartphone";
import TerminalIconData from "../icons/terminal";
import CodeIconData from "../icons/code";
import SettingsIconData from "../icons/settings";
import FileTextIconData from "../icons/file-text";
import FilePlusIconData from "../icons/file-plus";
import FileMinusIconData from "../icons/file-minus";
import FilePenIconData from "../icons/file-pen";
import FileSearchIconData from "../icons/file-search";
import FileCodeIconData from "../icons/file-code";
import FileVideoIconData from "../icons/file-video";
import FolderIconData from "../icons/folder";
import FolderPlusIconData from "../icons/folder-plus";
import FolderCogIconData from "../icons/folder-cog";
import FoldersIconData from "../icons/folders";
import FolderTreeIconData from "../icons/folder-tree";
import ImageIconData from "../icons/image";
import ImagePlayIconData from "../icons/image-play";
import MusicIconData from "../icons/music";
import CaptionsIconData from "../icons/captions";
import BoldIconData from "../icons/bold";
import ItalicIconData from "../icons/italic";
import UnderlineIconData from "../icons/underline";
import StrikethroughIconData from "../icons/strikethrough";
import Heading2IconData from "../icons/heading2";
import QuoteIconData from "../icons/quote";
import ListIconData from "../icons/list";
import ListOrderedIconData from "../icons/list-ordered";
import CodeAppIconData from "../icons/code-app";
import FinderAppIconData from "../icons/finder-app";
import MediaAppIconData from "../icons/media-app";
import PageAppIconData from "../icons/page-app";
import PortfolioAppIconData from "../icons/portfolio-app";
import CvAppIconData from "../icons/cv-app";
import HelpAppIconData from "../icons/help-app";
import SupportAppIconData from "../icons/support-app";
import StoryAppIconData from "../icons/story-app";
import CoursesAppIconData from "../icons/courses-app";
import TermsAppIconData from "../icons/terms-app";
import PrivacyAppIconData from "../icons/privacy-app";
import AcceptableUseAppIconData from "../icons/acceptable-use-app";
import CookiesAppIconData from "../icons/cookies-app";
import RefundsAppIconData from "../icons/refunds-app";
import AppsIconData from "../icons/apps";
import VideoGroupIconData from "../icons/video-group";
import ImageGroupIconData from "../icons/image-group";
import AudioGroupIconData from "../icons/audio-group";
import PdfGroupIconData from "../icons/pdf-group";
import AnimateGroupIconData from "../icons/animate-group";
import SubtitleGroupIconData from "../icons/subtitle-group";
import QueueIconData from "../icons/queue";
import ProIconData from "../icons/pro";
import VideoShrinkIconData from "../icons/video-shrink";
import FitSizeIconData from "../icons/fit-size";
import TrimIconData from "../icons/trim";
import ConvertIconData from "../icons/convert";
import VideoToGifIconData from "../icons/video-to-gif";
import ResizeIconData from "../icons/resize";
import MuteIconData from "../icons/mute";
import ImageShrinkIconData from "../icons/image-shrink";
import LongestEdgeIconData from "../icons/longest-edge";
import StripDataIconData from "../icons/strip-data";
import AudioShrinkIconData from "../icons/audio-shrink";
import VoiceIconData from "../icons/voice";
import PdfShrinkIconData from "../icons/pdf-shrink";
import GrayscaleIconData from "../icons/grayscale";
import MakeAnimationIconData from "../icons/make-animation";
import WriteSubtitlesIconData from "../icons/write-subtitles";
import TranscribeIconData from "../icons/transcribe";
import BurnInIconData from "../icons/burn-in";
import SubtitleTrackIconData from "../icons/subtitle-track";
import ToolsIconData from "../icons/tools";
import PlayIconData from "../icons/play";
import PauseIconData from "../icons/pause";
import NewIconData from "../icons/new";
import ProjectsIconData from "../icons/projects";
import FilesIconData from "../icons/files";
import AgentIconData from "../icons/agent";
import PackagesIconData from "../icons/packages";
import ShareIconData from "../icons/share";
import AllFilesIconData from "../icons/all-files";
import PublicIconData from "../icons/public";
import IconsViewIconData from "../icons/icons-view";
import ListViewIconData from "../icons/list-view";
import ColumnsViewIconData from "../icons/columns-view";
import GalleryViewIconData from "../icons/gallery-view";
import SmallTilesIconData from "../icons/small-tiles";
import LargeTilesIconData from "../icons/large-tiles";
import CommandKeyIconData from "../icons/command-key";
import ShiftKeyIconData from "../icons/shift-key";
import LayersIconData from "../icons/layers";
import BlocksIconData from "../icons/blocks";
import GripIconData from "../icons/grip";
import EyeOffIconData from "../icons/eye-off";
import UnlockIconData from "../icons/unlock";
import DuplicateIconData from "../icons/duplicate";
import AlignLeftIconData from "../icons/align-left";
import AlignCenterIconData from "../icons/align-center";
import AlignRightIconData from "../icons/align-right";
import PanIconData from "../icons/pan";
import FitScreenIconData from "../icons/fit-screen";
import PageBreakIconData from "../icons/page-break";
import PublishIconData from "../icons/publish";
import TemplateIconData from "../icons/template";
import VersionsIconData from "../icons/versions";
import SectionIconData from "../icons/section";
import TextIconData from "../icons/text";
import FormIconData from "../icons/form";
import SpreadsheetIconData from "../icons/spreadsheet";
import PresentationIconData from "../icons/presentation";
import RunSnipMarkData from "../icons/run-snip-mark";
import RunSnipWordmarkData from "../icons/run-snip-wordmark";
import IconGoogleData from "../icons/icon-google";
import IconGithubData from "../icons/icon-github";

export const ChevronRightIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronRightIconData);
export const ChevronIcon: IconComponent = ChevronRightIcon;
export const PathStepIcon: IconComponent = ChevronRightIcon;
export const ChevronLeftIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronLeftIconData);
export const ChevronDownIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronDownIconData);
export const DisclosureIcon: IconComponent = ChevronDownIcon;
export const ChevronUpIcon: IconComponent = /* @__PURE__ */ createIcon(ChevronUpIconData);
export const ArrowRightIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowRightIconData);
export const ArrowRight: IconComponent = ArrowRightIcon;
export const ArrowLeftIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowLeftIconData);
export const ArrowLeft: IconComponent = ArrowLeftIcon;
export const ArrowDownIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowDownIconData);
export const SortDownIcon: IconComponent = ArrowDownIcon;
export const ArrowUpIcon: IconComponent = /* @__PURE__ */ createIcon(ArrowUpIconData);
export const SortUpIcon: IconComponent = ArrowUpIcon;
export const CheckIcon: IconComponent = /* @__PURE__ */ createIcon(CheckIconData);
export const Check: IconComponent = CheckIcon;
export const XIcon: IconComponent = /* @__PURE__ */ createIcon(XIconData);
export const CloseIcon: IconComponent = XIcon;
export const X: IconComponent = XIcon;
export const PlusIcon: IconComponent = /* @__PURE__ */ createIcon(PlusIconData);
export const MinusIcon: IconComponent = /* @__PURE__ */ createIcon(MinusIconData);
export const MenuIcon: IconComponent = /* @__PURE__ */ createIcon(MenuIconData);
export const EllipsisIcon: IconComponent = /* @__PURE__ */ createIcon(EllipsisIconData);
export const SpinnerIcon: IconComponent = /* @__PURE__ */ createIcon(SpinnerIconData);
export const Loader2: IconComponent = SpinnerIcon;
export const Loader2Icon: IconComponent = SpinnerIcon;
export const SquareIcon: IconComponent = /* @__PURE__ */ createIcon(SquareIconData);
export const SearchIcon: IconComponent = /* @__PURE__ */ createIcon(SearchIconData);
export const ExternalIcon: IconComponent = /* @__PURE__ */ createIcon(ExternalIconData);
export const CopyIcon: IconComponent = /* @__PURE__ */ createIcon(CopyIconData);
export const TrashIcon: IconComponent = /* @__PURE__ */ createIcon(TrashIconData);
export const Trash2Icon: IconComponent = TrashIcon;
export const DownloadIcon: IconComponent = /* @__PURE__ */ createIcon(DownloadIconData);
export const UploadIcon: IconComponent = /* @__PURE__ */ createIcon(UploadIconData);
export const ExternalLinkIcon: IconComponent = /* @__PURE__ */ createIcon(ExternalLinkIconData);
export const ExternalLink: IconComponent = ExternalLinkIcon;
export const PencilIcon: IconComponent = /* @__PURE__ */ createIcon(PencilIconData);
export const SaveIcon: IconComponent = /* @__PURE__ */ createIcon(SaveIconData);
export const EraserIcon: IconComponent = /* @__PURE__ */ createIcon(EraserIconData);
export const RefreshCwIcon: IconComponent = /* @__PURE__ */ createIcon(RefreshCwIconData);
export const RotateCcwIcon: IconComponent = /* @__PURE__ */ createIcon(RotateCcwIconData);
export const AgainIcon: IconComponent = RotateCcwIcon;
export const RotateCwIcon: IconComponent = /* @__PURE__ */ createIcon(RotateCwIconData);
export const RotateCw: IconComponent = RotateCwIcon;
export const Undo2Icon: IconComponent = /* @__PURE__ */ createIcon(Undo2IconData);
export const Redo2Icon: IconComponent = /* @__PURE__ */ createIcon(Redo2IconData);
export const ScissorsIcon: IconComponent = /* @__PURE__ */ createIcon(ScissorsIconData);
export const ClipboardIcon: IconComponent = /* @__PURE__ */ createIcon(ClipboardIconData);
export const ClipboardPasteIcon: IconComponent = /* @__PURE__ */ createIcon(ClipboardPasteIconData);
export const PinIcon: IconComponent = /* @__PURE__ */ createIcon(PinIconData);
export const FoldVerticalIcon: IconComponent = /* @__PURE__ */ createIcon(FoldVerticalIconData);
export const WrapTextIcon: IconComponent = /* @__PURE__ */ createIcon(WrapTextIconData);
export const LinkIcon: IconComponent = /* @__PURE__ */ createIcon(LinkIconData);
export const Link2Icon: IconComponent = LinkIcon;
export const PaperclipIcon: IconComponent = /* @__PURE__ */ createIcon(PaperclipIconData);
export const LogOutIcon: IconComponent = /* @__PURE__ */ createIcon(LogOutIconData);
export const MaximizeIcon: IconComponent = /* @__PURE__ */ createIcon(MaximizeIconData);
export const Maximize2: IconComponent = MaximizeIcon;
export const MinimizeIcon: IconComponent = /* @__PURE__ */ createIcon(MinimizeIconData);
export const Minimize2: IconComponent = MinimizeIcon;
export const PanelLeftCloseIcon: IconComponent = /* @__PURE__ */ createIcon(PanelLeftCloseIconData);
export const PanelLeftOpenIcon: IconComponent = /* @__PURE__ */ createIcon(PanelLeftOpenIconData);
export const SquareArrowOutUpRightIcon: IconComponent = /* @__PURE__ */ createIcon(SquareArrowOutUpRightIconData);
export const TriangleAlertIcon: IconComponent = /* @__PURE__ */ createIcon(TriangleAlertIconData);
export const WarnIcon: IconComponent = TriangleAlertIcon;
export const InfoIcon: IconComponent = /* @__PURE__ */ createIcon(InfoIconData);
export const CircleCheckIcon: IconComponent = /* @__PURE__ */ createIcon(CircleCheckIconData);
export const OctagonXIcon: IconComponent = /* @__PURE__ */ createIcon(OctagonXIconData);
export const BanIcon: IconComponent = /* @__PURE__ */ createIcon(BanIconData);
export const LockIcon: IconComponent = /* @__PURE__ */ createIcon(LockIconData);
export const LockedIcon: IconComponent = LockIcon;
export const KeyRoundIcon: IconComponent = /* @__PURE__ */ createIcon(KeyRoundIconData);
export const ShieldIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldIconData);
export const ShieldAlertIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldAlertIconData);
export const ShieldPlusIcon: IconComponent = /* @__PURE__ */ createIcon(ShieldPlusIconData);
export const SparklesIcon: IconComponent = /* @__PURE__ */ createIcon(SparklesIconData);
export const Sparkles: IconComponent = SparklesIcon;
export const StarIcon: IconComponent = /* @__PURE__ */ createIcon(StarIconData);
export const LightbulbIcon: IconComponent = /* @__PURE__ */ createIcon(LightbulbIconData);
export const Lightbulb: IconComponent = LightbulbIcon;
export const EyeIcon: IconComponent = /* @__PURE__ */ createIcon(EyeIconData);
export const ClockIcon: IconComponent = /* @__PURE__ */ createIcon(ClockIconData);
export const RecentsIcon: IconComponent = ClockIcon;
export const GaugeIcon: IconComponent = /* @__PURE__ */ createIcon(GaugeIconData);
export const GemIcon: IconComponent = /* @__PURE__ */ createIcon(GemIconData);
export const HomeIcon: IconComponent = /* @__PURE__ */ createIcon(HomeIconData);
export const Home: IconComponent = HomeIcon;
export const UserRoundIcon: IconComponent = /* @__PURE__ */ createIcon(UserRoundIconData);
export const UsersIcon: IconComponent = /* @__PURE__ */ createIcon(UsersIconData);
export const MailIcon: IconComponent = /* @__PURE__ */ createIcon(MailIconData);
export const MessageSquareIcon: IconComponent = /* @__PURE__ */ createIcon(MessageSquareIconData);
export const BotIcon: IconComponent = /* @__PURE__ */ createIcon(BotIconData);
export const BugIcon: IconComponent = /* @__PURE__ */ createIcon(BugIconData);
export const BookOpenIcon: IconComponent = /* @__PURE__ */ createIcon(BookOpenIconData);
export const LibraryIcon: IconComponent = /* @__PURE__ */ createIcon(LibraryIconData);
export const CreditCardIcon: IconComponent = /* @__PURE__ */ createIcon(CreditCardIconData);
export const TagIcon: IconComponent = /* @__PURE__ */ createIcon(TagIconData);
export const PackageIcon: IconComponent = /* @__PURE__ */ createIcon(PackageIconData);
export const ArchiveIcon: IconComponent = /* @__PURE__ */ createIcon(ArchiveIconData);
export const MapIcon: IconComponent = /* @__PURE__ */ createIcon(MapIconData);
export const LifeBuoyIcon: IconComponent = /* @__PURE__ */ createIcon(LifeBuoyIconData);
export const WrenchIcon: IconComponent = /* @__PURE__ */ createIcon(WrenchIconData);
export const PlugIcon: IconComponent = /* @__PURE__ */ createIcon(PlugIconData);
export const PlugZapIcon: IconComponent = /* @__PURE__ */ createIcon(PlugZapIconData);
export const ServerIcon: IconComponent = /* @__PURE__ */ createIcon(ServerIconData);
export const CloudIcon: IconComponent = /* @__PURE__ */ createIcon(CloudIconData);
export const GlobeIcon: IconComponent = /* @__PURE__ */ createIcon(GlobeIconData);
export const MonitorIcon: IconComponent = /* @__PURE__ */ createIcon(MonitorIconData);
export const DesktopIcon: IconComponent = MonitorIcon;
export const TabletIcon: IconComponent = /* @__PURE__ */ createIcon(TabletIconData);
export const SmartphoneIcon: IconComponent = /* @__PURE__ */ createIcon(SmartphoneIconData);
export const PhoneIcon: IconComponent = SmartphoneIcon;
export const TerminalIcon: IconComponent = /* @__PURE__ */ createIcon(TerminalIconData);
export const Terminal: IconComponent = TerminalIcon;
export const CodeIcon: IconComponent = /* @__PURE__ */ createIcon(CodeIconData);
export const SettingsIcon: IconComponent = /* @__PURE__ */ createIcon(SettingsIconData);
export const SlidersHorizontalIcon: IconComponent = SettingsIcon;
export const FileTextIcon: IconComponent = /* @__PURE__ */ createIcon(FileTextIconData);
export const FilePlusIcon: IconComponent = /* @__PURE__ */ createIcon(FilePlusIconData);
export const FileMinusIcon: IconComponent = /* @__PURE__ */ createIcon(FileMinusIconData);
export const FilePenIcon: IconComponent = /* @__PURE__ */ createIcon(FilePenIconData);
export const FileSearchIcon: IconComponent = /* @__PURE__ */ createIcon(FileSearchIconData);
export const FileCodeIcon: IconComponent = /* @__PURE__ */ createIcon(FileCodeIconData);
export const FileCode2: IconComponent = FileCodeIcon;
export const FileVideoIcon: IconComponent = /* @__PURE__ */ createIcon(FileVideoIconData);
export const FolderIcon: IconComponent = /* @__PURE__ */ createIcon(FolderIconData);
export const FolderPlusIcon: IconComponent = /* @__PURE__ */ createIcon(FolderPlusIconData);
export const FolderCogIcon: IconComponent = /* @__PURE__ */ createIcon(FolderCogIconData);
export const FoldersIcon: IconComponent = /* @__PURE__ */ createIcon(FoldersIconData);
export const FolderTreeIcon: IconComponent = /* @__PURE__ */ createIcon(FolderTreeIconData);
export const ImageIcon: IconComponent = /* @__PURE__ */ createIcon(ImageIconData);
export const ImagePlayIcon: IconComponent = /* @__PURE__ */ createIcon(ImagePlayIconData);
export const MusicIcon: IconComponent = /* @__PURE__ */ createIcon(MusicIconData);
export const CaptionsIcon: IconComponent = /* @__PURE__ */ createIcon(CaptionsIconData);
export const BoldIcon: IconComponent = /* @__PURE__ */ createIcon(BoldIconData);
export const ItalicIcon: IconComponent = /* @__PURE__ */ createIcon(ItalicIconData);
export const UnderlineIcon: IconComponent = /* @__PURE__ */ createIcon(UnderlineIconData);
export const StrikethroughIcon: IconComponent = /* @__PURE__ */ createIcon(StrikethroughIconData);
export const Heading2Icon: IconComponent = /* @__PURE__ */ createIcon(Heading2IconData);
export const QuoteIcon: IconComponent = /* @__PURE__ */ createIcon(QuoteIconData);
export const ListIcon: IconComponent = /* @__PURE__ */ createIcon(ListIconData);
export const ListOrderedIcon: IconComponent = /* @__PURE__ */ createIcon(ListOrderedIconData);
export const CodeAppIcon: IconComponent = /* @__PURE__ */ createIcon(CodeAppIconData);
export const FinderAppIcon: IconComponent = /* @__PURE__ */ createIcon(FinderAppIconData);
export const MediaAppIcon: IconComponent = /* @__PURE__ */ createIcon(MediaAppIconData);
export const PageAppIcon: IconComponent = /* @__PURE__ */ createIcon(PageAppIconData);
export const PortfolioAppIcon: IconComponent = /* @__PURE__ */ createIcon(PortfolioAppIconData);
export const CvAppIcon: IconComponent = /* @__PURE__ */ createIcon(CvAppIconData);
export const HelpAppIcon: IconComponent = /* @__PURE__ */ createIcon(HelpAppIconData);
export const SupportAppIcon: IconComponent = /* @__PURE__ */ createIcon(SupportAppIconData);
export const StoryAppIcon: IconComponent = /* @__PURE__ */ createIcon(StoryAppIconData);
export const CoursesAppIcon: IconComponent = /* @__PURE__ */ createIcon(CoursesAppIconData);
export const TermsAppIcon: IconComponent = /* @__PURE__ */ createIcon(TermsAppIconData);
export const PrivacyAppIcon: IconComponent = /* @__PURE__ */ createIcon(PrivacyAppIconData);
export const AcceptableUseAppIcon: IconComponent = /* @__PURE__ */ createIcon(AcceptableUseAppIconData);
export const CookiesAppIcon: IconComponent = /* @__PURE__ */ createIcon(CookiesAppIconData);
export const RefundsAppIcon: IconComponent = /* @__PURE__ */ createIcon(RefundsAppIconData);
export const AppsIcon: IconComponent = /* @__PURE__ */ createIcon(AppsIconData);
export const VideoGroupIcon: IconComponent = /* @__PURE__ */ createIcon(VideoGroupIconData);
export const VideosKindIcon: IconComponent = VideoGroupIcon;
export const ImageGroupIcon: IconComponent = /* @__PURE__ */ createIcon(ImageGroupIconData);
export const ImagesKindIcon: IconComponent = ImageGroupIcon;
export const AudioGroupIcon: IconComponent = /* @__PURE__ */ createIcon(AudioGroupIconData);
export const AudioKindIcon: IconComponent = AudioGroupIcon;
export const PdfGroupIcon: IconComponent = /* @__PURE__ */ createIcon(PdfGroupIconData);
export const DocumentsKindIcon: IconComponent = PdfGroupIcon;
export const AnimateGroupIcon: IconComponent = /* @__PURE__ */ createIcon(AnimateGroupIconData);
export const SubtitleGroupIcon: IconComponent = /* @__PURE__ */ createIcon(SubtitleGroupIconData);
export const QueueIcon: IconComponent = /* @__PURE__ */ createIcon(QueueIconData);
export const ProIcon: IconComponent = /* @__PURE__ */ createIcon(ProIconData);
export const VideoShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(VideoShrinkIconData);
export const FitSizeIcon: IconComponent = /* @__PURE__ */ createIcon(FitSizeIconData);
export const TrimIcon: IconComponent = /* @__PURE__ */ createIcon(TrimIconData);
export const ConvertIcon: IconComponent = /* @__PURE__ */ createIcon(ConvertIconData);
export const VideoToGifIcon: IconComponent = /* @__PURE__ */ createIcon(VideoToGifIconData);
export const ResizeIcon: IconComponent = /* @__PURE__ */ createIcon(ResizeIconData);
export const MuteIcon: IconComponent = /* @__PURE__ */ createIcon(MuteIconData);
export const ImageShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(ImageShrinkIconData);
export const LongestEdgeIcon: IconComponent = /* @__PURE__ */ createIcon(LongestEdgeIconData);
export const StripDataIcon: IconComponent = /* @__PURE__ */ createIcon(StripDataIconData);
export const AudioShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(AudioShrinkIconData);
export const VoiceIcon: IconComponent = /* @__PURE__ */ createIcon(VoiceIconData);
export const PdfShrinkIcon: IconComponent = /* @__PURE__ */ createIcon(PdfShrinkIconData);
export const GrayscaleIcon: IconComponent = /* @__PURE__ */ createIcon(GrayscaleIconData);
export const MakeAnimationIcon: IconComponent = /* @__PURE__ */ createIcon(MakeAnimationIconData);
export const WriteSubtitlesIcon: IconComponent = /* @__PURE__ */ createIcon(WriteSubtitlesIconData);
export const TranscribeIcon: IconComponent = /* @__PURE__ */ createIcon(TranscribeIconData);
export const BurnInIcon: IconComponent = /* @__PURE__ */ createIcon(BurnInIconData);
export const SubtitleTrackIcon: IconComponent = /* @__PURE__ */ createIcon(SubtitleTrackIconData);
export const ToolsIcon: IconComponent = /* @__PURE__ */ createIcon(ToolsIconData);
export const PlayIcon: IconComponent = /* @__PURE__ */ createIcon(PlayIconData);
export const PauseIcon: IconComponent = /* @__PURE__ */ createIcon(PauseIconData);
export const NewIcon: IconComponent = /* @__PURE__ */ createIcon(NewIconData);
export const ProjectsIcon: IconComponent = /* @__PURE__ */ createIcon(ProjectsIconData);
export const FilesIcon: IconComponent = /* @__PURE__ */ createIcon(FilesIconData);
export const AgentIcon: IconComponent = /* @__PURE__ */ createIcon(AgentIconData);
export const PackagesIcon: IconComponent = /* @__PURE__ */ createIcon(PackagesIconData);
export const ShareIcon: IconComponent = /* @__PURE__ */ createIcon(ShareIconData);
export const AllFilesIcon: IconComponent = /* @__PURE__ */ createIcon(AllFilesIconData);
export const PublicIcon: IconComponent = /* @__PURE__ */ createIcon(PublicIconData);
export const IconsViewIcon: IconComponent = /* @__PURE__ */ createIcon(IconsViewIconData);
export const ListViewIcon: IconComponent = /* @__PURE__ */ createIcon(ListViewIconData);
export const ColumnsViewIcon: IconComponent = /* @__PURE__ */ createIcon(ColumnsViewIconData);
export const GalleryViewIcon: IconComponent = /* @__PURE__ */ createIcon(GalleryViewIconData);
export const SmallTilesIcon: IconComponent = /* @__PURE__ */ createIcon(SmallTilesIconData);
export const LargeTilesIcon: IconComponent = /* @__PURE__ */ createIcon(LargeTilesIconData);
export const CommandKeyIcon: IconComponent = /* @__PURE__ */ createIcon(CommandKeyIconData);
export const ShiftKeyIcon: IconComponent = /* @__PURE__ */ createIcon(ShiftKeyIconData);
export const LayersIcon: IconComponent = /* @__PURE__ */ createIcon(LayersIconData);
export const BlocksIcon: IconComponent = /* @__PURE__ */ createIcon(BlocksIconData);
export const GripIcon: IconComponent = /* @__PURE__ */ createIcon(GripIconData);
export const EyeOffIcon: IconComponent = /* @__PURE__ */ createIcon(EyeOffIconData);
export const UnlockIcon: IconComponent = /* @__PURE__ */ createIcon(UnlockIconData);
export const DuplicateIcon: IconComponent = /* @__PURE__ */ createIcon(DuplicateIconData);
export const AlignLeftIcon: IconComponent = /* @__PURE__ */ createIcon(AlignLeftIconData);
export const AlignCenterIcon: IconComponent = /* @__PURE__ */ createIcon(AlignCenterIconData);
export const AlignRightIcon: IconComponent = /* @__PURE__ */ createIcon(AlignRightIconData);
export const PanIcon: IconComponent = /* @__PURE__ */ createIcon(PanIconData);
export const FitScreenIcon: IconComponent = /* @__PURE__ */ createIcon(FitScreenIconData);
export const PageBreakIcon: IconComponent = /* @__PURE__ */ createIcon(PageBreakIconData);
export const PublishIcon: IconComponent = /* @__PURE__ */ createIcon(PublishIconData);
export const TemplateIcon: IconComponent = /* @__PURE__ */ createIcon(TemplateIconData);
export const VersionsIcon: IconComponent = /* @__PURE__ */ createIcon(VersionsIconData);
export const SectionIcon: IconComponent = /* @__PURE__ */ createIcon(SectionIconData);
export const TextIcon: IconComponent = /* @__PURE__ */ createIcon(TextIconData);
export const FormIcon: IconComponent = /* @__PURE__ */ createIcon(FormIconData);
export const SpreadsheetIcon: IconComponent = /* @__PURE__ */ createIcon(SpreadsheetIconData);
export const PresentationIcon: IconComponent = /* @__PURE__ */ createIcon(PresentationIconData);
export const RunSnipMark: IconComponent = /* @__PURE__ */ createIcon(RunSnipMarkData);
export const RunSnipWordmark: IconComponent = /* @__PURE__ */ createIcon(RunSnipWordmarkData);
export const IconGoogle: IconComponent = /* @__PURE__ */ createIcon(IconGoogleData);
export const IconGithub: IconComponent = /* @__PURE__ */ createIcon(IconGithubData);
